/**
 * Smart Agricultural Procurement & Slot Management Platform (KrishiSetu)
 * Master Data: 22 Scheduled Indian Languages, Crops, Centers & Historical Sales
 */

const SCHEDULED_LANGUAGES = [
  { code: 'en', nameEn: 'English', nameNative: 'English', region: 'Global / Official' },
  { code: 'as', nameEn: 'Assamese', nameNative: 'অসমীয়া', region: 'Assam' },
  { code: 'bn', nameEn: 'Bengali', nameNative: 'বাংলা', region: 'West Bengal / Tripura' },
  { code: 'brx', nameEn: 'Bodo', nameNative: 'बड़ो', region: 'Assam' },
  { code: 'doi', nameEn: 'Dogri', nameNative: 'डोगरी', region: 'Jammu & Kashmir' },
  { code: 'gu', nameEn: 'Gujarati', nameNative: 'ગુજરાતી', region: 'Gujarat' },
  { code: 'hi', nameEn: 'Hindi', nameNative: 'हिन्दी', region: 'Northern / Central India' },
  { code: 'kn', nameEn: 'Kannada', nameNative: 'ಕನ್ನಡ', region: 'Karnataka' },
  { code: 'ks', nameEn: 'Kashmiri', nameNative: 'کٲشُر / कश्मीरी', region: 'Jammu & Kashmir' },
  { code: 'kok', nameEn: 'Konkani', nameNative: 'कोंकणी', region: 'Goa / Maharashtra' },
  { code: 'mai', nameEn: 'Maithili', nameNative: 'मैथिली', region: 'Bihar' },
  { code: 'ml', nameEn: 'Malayalam', nameNative: 'മലയാളം', region: 'Kerala' },
  { code: 'mni', nameEn: 'Manipuri (Meitei)', nameNative: 'মৈতৈলোন্', region: 'Manipur' },
  { code: 'mr', nameEn: 'Marathi', nameNative: 'मराठी', region: 'Maharashtra' },
  { code: 'ne', nameEn: 'Nepali', nameNative: 'नेपाली', region: 'Sikkim / West Bengal' },
  { code: 'or', nameEn: 'Odia', nameNative: 'ଓଡ଼ିଆ', region: 'Odisha' },
  { code: 'pa', nameEn: 'Punjabi', nameNative: 'ਪੰਜਾਬੀ', region: 'Punjab / Haryana' },
  { code: 'sa', nameEn: 'Sanskrit', nameNative: 'संस्कृतम्', region: 'Classical India' },
  { code: 'sat', nameEn: 'Santali', nameNative: 'ᱥᱟᱱᱛᱟᱲᱤ', region: 'Jharkhand / Odisha' },
  { code: 'sd', nameEn: 'Sindhi', nameNative: 'سنڌي / सिंधी', region: 'Sindh Heritage' },
  { code: 'ta', nameEn: 'Tamil', nameNative: 'தமிழ்', region: 'Tamil Nadu' },
  { code: 'te', nameEn: 'Telugu', nameNative: 'తెలుగు', region: 'Andhra Pradesh / Telangana' },
  { code: 'ur', nameEn: 'Urdu', nameNative: 'اردو', region: 'National / Official' }
];

const INITIAL_FARMERS = [
  {
    farmerId: 'PB-FARM-99402',
    name: 'Ramesh Singh',
    phone: '9872100412',
    aadhaar: 'XXXX-XXXX-4821',
    bankMasked: 'HDFC Bank - A/C ..8921',
    bankIfsc: 'HDFC0001092',
    address: 'Village Alour, Khanna Tehsil, Ludhiana, Punjab - 141401',
    registeredAt: '2026-09-15T09:00:00.000Z'
  }
];

const INITIAL_CROPS = [
  {
    id: 'crop-1',
    name: 'Wheat (Gehun / Kanak)',
    code: 'WHEAT',
    msp: 2275,
    unit: 'Quintal',
    maxMoisture: 12.0,
    standardWeightTolerance: 0.5,
    qualityGrades: {
      A: { bonus: 50, desc: 'Moisture < 11%, Lustrous, No foreign matter' },
      B: { bonus: 0, desc: 'Moisture 11-12%, Standard Fair Average Quality' },
      C: { bonus: -75, desc: 'Moisture 12.1-14%, Minor dockage' }
    }
  },
  {
    id: 'crop-2',
    name: 'Paddy / Rice (Dhan / Jhona)',
    code: 'PADDY',
    msp: 2320,
    unit: 'Quintal',
    maxMoisture: 14.0,
    qualityGrades: {
      A: { bonus: 60, desc: 'Grade A Long Grain, Moisture < 13%' },
      B: { bonus: 0, desc: 'Common Paddy, FAQ standard' },
      C: { bonus: -80, desc: 'Moisture 14.1-16%, High chaff' }
    }
  },
  {
    id: 'crop-3',
    name: 'Mustard (Sarson)',
    code: 'MUSTARD',
    msp: 5650,
    unit: 'Quintal',
    maxMoisture: 8.0,
    qualityGrades: {
      A: { bonus: 100, desc: 'High Oil content (>40%), Moisture < 7%' },
      B: { bonus: 0, desc: 'Standard Oil content (38-40%)' },
      C: { bonus: -120, desc: 'Moisture > 8.5%, High foreign seed' }
    }
  },
  {
    id: 'crop-4',
    name: 'Cotton (Kapas)',
    code: 'COTTON',
    msp: 7122,
    unit: 'Quintal',
    maxMoisture: 8.5,
    qualityGrades: {
      A: { bonus: 150, desc: 'Long Staple, Bright White, Low Trash' },
      B: { bonus: 0, desc: 'Medium Staple, Standard' },
      C: { bonus: -150, desc: 'High yellow stain, High trash' }
    }
  },
  {
    id: 'crop-5',
    name: 'Maize / Corn (Makka)',
    code: 'MAIZE',
    msp: 2090,
    unit: 'Quintal',
    maxMoisture: 13.0,
    qualityGrades: {
      A: { bonus: 40, desc: 'Sound grains, Moisture < 12%' },
      B: { bonus: 0, desc: 'Standard FAQ' },
      C: { bonus: -60, desc: 'Discolored, Moisture > 13.5%' }
    }
  },
  {
    id: 'crop-6',
    name: 'Soyabean (Soybean)',
    code: 'SOYABEAN',
    msp: 4892,
    unit: 'Quintal',
    maxMoisture: 10.0,
    qualityGrades: {
      A: { bonus: 80, desc: 'Clean, Yellow, Moisture < 9%' },
      B: { bonus: 0, desc: 'Standard FAQ (9-10% moisture)' },
      C: { bonus: -100, desc: 'Split seeds, High moisture' }
    }
  }
];

const INITIAL_CENTERS = [
  {
    id: 'center-1',
    name: 'Khanna Central Grain Mandi',
    district: 'Ludhiana',
    state: 'Punjab',
    pincode: '141401',
    distanceKm: 4.8,
    dailyCapacityQuintals: 2500,
    hourlySlotCapacityQuintals: 300,
    currentBookedTodayQuintals: 1980, // >70% capacity
    operatingHours: '08:00 AM - 07:00 PM',
    weighbridgesActive: 3,
    qualityCounters: 2,
    currentWaitMins: 22,
    managerName: 'Suresh Kumar Verma',
    phone: '+91 98765 43210',
    facilities: ['Automated Weighbridge', 'Moisture Testing Lab', 'Farmer Rest Shed', 'Covered Bay', 'Priority Fast-Track Lane']
  },
  {
    id: 'center-2',
    name: 'Samrala Agro Procurement Yard',
    district: 'Ludhiana',
    state: 'Punjab',
    pincode: '141114',
    distanceKm: 12.3,
    dailyCapacityQuintals: 1800,
    hourlySlotCapacityQuintals: 220,
    currentBookedTodayQuintals: 950,
    operatingHours: '08:00 AM - 06:00 PM',
    weighbridgesActive: 2,
    qualityCounters: 1,
    currentWaitMins: 14,
    managerName: 'Harpreet Singh',
    phone: '+91 98765 11223',
    facilities: ['Digital Weighbridge', 'Moisture Analyzer', 'Drinking Water', 'Rest Area']
  },
  {
    id: 'center-3',
    name: 'Sirhind Cooperative Procurement Hub',
    district: 'Fatehgarh Sahib',
    state: 'Punjab',
    pincode: '140406',
    distanceKm: 18.5,
    dailyCapacityQuintals: 3200,
    hourlySlotCapacityQuintals: 400,
    currentBookedTodayQuintals: 2900,
    operatingHours: '07:30 AM - 08:00 PM',
    weighbridgesActive: 4,
    qualityCounters: 3,
    currentWaitMins: 38,
    managerName: 'Rajeshwar Patil',
    phone: '+91 98765 88990',
    facilities: ['Heavy Duty Weighbridge', 'Direct Rail Siding', 'Automated Lab', 'Priority Lane']
  },
  {
    id: 'center-4',
    name: 'Ambala Cantonment Agro Terminal',
    district: 'Ambala',
    state: 'Haryana',
    pincode: '133001',
    distanceKm: 34.0,
    dailyCapacityQuintals: 2200,
    hourlySlotCapacityQuintals: 260,
    currentBookedTodayQuintals: 1100,
    operatingHours: '08:00 AM - 06:30 PM',
    weighbridgesActive: 2,
    qualityCounters: 2,
    currentWaitMins: 18,
    managerName: 'Virender Hooda',
    phone: '+91 98765 33445',
    facilities: ['Electronic Scales', 'Grading Lab', 'DBT Helpdesk']
  },
  {
    id: 'center-5',
    name: 'Karnal Regional Agro Procurement Center',
    district: 'Karnal',
    state: 'Haryana',
    pincode: '132001',
    distanceKm: 52.4,
    dailyCapacityQuintals: 3500,
    hourlySlotCapacityQuintals: 420,
    currentBookedTodayQuintals: 1680,
    operatingHours: '07:00 AM - 07:30 PM',
    weighbridgesActive: 4,
    qualityCounters: 3,
    currentWaitMins: 16,
    managerName: 'Devender Sharma',
    phone: '+91 98765 77889',
    facilities: ['Multi-Lane Automated Weighbridge', 'Moisture Testing Counter', 'Farmer Canteen', 'Covered Unloading Yard', 'Priority Fast-Track Lane']
  },
  {
    id: 'center-6',
    name: 'Moga Grain Terminal',
    district: 'Moga',
    state: 'Punjab',
    pincode: '142001',
    distanceKm: 68.0,
    dailyCapacityQuintals: 4200,
    hourlySlotCapacityQuintals: 500,
    currentBookedTodayQuintals: 3100,
    operatingHours: '06:30 AM - 08:30 PM',
    weighbridgesActive: 5,
    qualityCounters: 4,
    currentWaitMins: 25,
    managerName: 'Balwinder Singh Dhillon',
    phone: '+91 98765 44556',
    facilities: ['Bulk Silo Conveyor', 'Direct Rail Depot', 'Instant Moisture Sensor', 'Fast-Track Queue']
  },
  {
    id: 'center-7',
    name: 'Patiala Mandi Complex',
    district: 'Patiala',
    state: 'Punjab',
    pincode: '147001',
    distanceKm: 42.1,
    dailyCapacityQuintals: 2800,
    hourlySlotCapacityQuintals: 320,
    currentBookedTodayQuintals: 1450,
    operatingHours: '08:00 AM - 07:00 PM',
    weighbridgesActive: 3,
    qualityCounters: 2,
    currentWaitMins: 19,
    managerName: 'Jasmeet Kaur',
    phone: '+91 98765 66778',
    facilities: ['Electronic Weighbridge', 'DBT Help Counter', 'Kisan Bhavan', 'Covered Shed', 'Fast-Track Lane']
  }
];

const INITIAL_BOOKINGS = [
  {
    id: 'KS-2026-PB-08492',
    farmerName: 'Ramesh Singh',
    farmerPhone: '9872100412',
    farmerAadhaarMasked: 'XXXX-XXXX-4821',
    farmerId: 'PB-FARM-99402',
    bankAccountMasked: 'HDFC Bank - A/C ..8921',
    bankIfsc: 'HDFC0001092',
    villageAddress: 'Village Alour, Khanna Tehsil, Ludhiana',
    centerId: 'center-1',
    centerName: 'Khanna Central Grain Mandi',
    cropId: 'crop-1',
    cropName: 'Wheat',
    declaredQuantityQuintals: 65,
    estimatedPayout: 147875,
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledSlot: '10:00 AM - 11:00 AM',
    vehicleNo: 'PB 10 CU 4829 (Tractor Trolley)',
    isPriorityHighYield: true, // Priority <= 100 Qtl
    otpCode: '8492',
    status: 'ACTIVE_QUEUE',
    queueToken: 'T-104',
    queuePosition: 2,
    estimatedWaitMins: 16,
    checkInTime: '09:48 AM',
    weighment: {
      grossWeightKg: 10700,
      tareWeightKg: 4200,
      netWeightKg: 6500,
      netWeightQuintals: 65.0,
      moisturePercent: 11.4,
      foreignMatterPercent: 0.4,
      assignedGrade: 'A',
      bonusPerQtl: 50,
      deductionPerQtl: 0,
      finalRatePerQtl: 2325,
      totalGrossAmount: 151125,
      mandiCessDeduction: 0,
      netPayableAmount: 151125,
      weighedBy: 'Operator Vikram (Scale #1)',
      weighedAt: '10:15 AM'
    },
    paymentLifecycle: {
      currentStage: 3,
      submittedAt: 'Today, 09:48 AM',
      qualityApprovedAt: 'Today, 10:22 AM',
      paymentInitiatedAt: 'Today, 10:35 AM',
      paymentCompletedAt: null,
      dbtBatchId: 'DBT-2026-PB-009182',
      utrNumber: 'PUNBH26070982143',
      paymentMethod: 'Direct Benefit Transfer (PFMS/Aadhaar Bridge)'
    },
    smsAlertsSent: [
      { type: 'CONFIRMATION', time: 'Yesterday, 04:30 PM', text: 'KrishiSetu: Slot CONFIRMED for Wheat (65 Qtl). Gate OTP: 8492. Pass Ref: KS-2026-PB-08492.' },
      { type: 'CHECKIN_TOKEN', time: 'Today, 09:48 AM', text: 'KrishiSetu: Check-in Verified via OTP. Issued Token: T-104. Current Position: #2 in queue.' },
      { type: 'QUALITY_PASS', time: 'Today, 10:25 AM', text: 'KrishiSetu: Quality Grade A Approved (Moisture 11.4%). Verified Net: 65.00 Qtl. Total: Rs 1,51,125.' }
    ]
  },
  {
    id: 'KS-2026-PB-08493',
    farmerName: 'Gurpreet Singh Dhillon',
    farmerPhone: '9814055672',
    farmerAadhaarMasked: 'XXXX-XXXX-9102',
    farmerId: 'PB-FARM-33109',
    bankAccountMasked: 'SBI - A/C ..4410',
    bankIfsc: 'SBIN0004928',
    villageAddress: 'Village Bija, Samrala, Ludhiana',
    centerId: 'center-1',
    centerName: 'Khanna Central Grain Mandi',
    cropId: 'crop-1',
    cropName: 'Wheat',
    declaredQuantityQuintals: 120,
    estimatedPayout: 273000,
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledSlot: '09:00 AM - 10:00 AM',
    vehicleNo: 'PB 23 J 9901 (Eicher Truck)',
    isPriorityHighYield: false, // > 100 Qtl (Standard queue)
    otpCode: '3310',
    status: 'PAYMENT_COMPLETED',
    queueToken: 'T-101',
    queuePosition: 0,
    estimatedWaitMins: 0,
    checkInTime: '08:50 AM',
    weighment: {
      grossWeightKg: 18200,
      tareWeightKg: 6200,
      netWeightKg: 12000,
      netWeightQuintals: 120.0,
      moisturePercent: 11.8,
      foreignMatterPercent: 0.5,
      assignedGrade: 'B',
      bonusPerQtl: 0,
      deductionPerQtl: 0,
      finalRatePerQtl: 2275,
      totalGrossAmount: 273000,
      mandiCessDeduction: 0,
      netPayableAmount: 273000,
      weighedBy: 'Operator Vikram (Scale #2)',
      weighedAt: '09:20 AM'
    },
    paymentLifecycle: {
      currentStage: 4,
      submittedAt: 'Today, 08:50 AM',
      qualityApprovedAt: 'Today, 09:30 AM',
      paymentInitiatedAt: 'Today, 09:45 AM',
      paymentCompletedAt: 'Today, 10:10 AM',
      dbtBatchId: 'DBT-2026-PB-009170',
      utrNumber: 'SBIN00492810931',
      paymentMethod: 'Direct Benefit Transfer (DBT-PFMS)'
    },
    smsAlertsSent: [
      { type: 'CONFIRMATION', time: 'Yesterday, 02:00 PM', text: 'Slot Confirmed: Ref KS-2026-PB-08493' },
      { type: 'PAYMENT_COMPLETED', time: 'Today, 10:10 AM', text: 'KrishiSetu DBT Alert: Rs 2,73,000 credited to SBI A/C ..4410 via UTR: SBIN00492810931.' }
    ]
  }
];

// Historical Sales Data for Farmer Profile
const HISTORICAL_SALES = [
  {
    saleId: 'SALE-2025-PB-7810',
    cropName: 'Paddy (Dhan FAQ)',
    deliveredDate: '18 Oct 2025',
    mandiName: 'Khanna Central Grain Mandi',
    netWeightQtl: 85.50,
    qualityGrade: 'Grade A (Moisture 12.2%)',
    ratePerQtl: 2320,
    totalDisbursed: 198360,
    dbtStatus: 'Credited (100% Complete)',
    utrNumber: 'HDFCR52025101892'
  },
  {
    saleId: 'SALE-2025-PB-3419',
    cropName: 'Wheat (Kanak PBW-550)',
    deliveredDate: '12 Apr 2025',
    mandiName: 'Khanna Central Grain Mandi',
    netWeightQtl: 72.00,
    qualityGrade: 'Grade A (+Rs 50 Bonus)',
    ratePerQtl: 2275,
    totalDisbursed: 163800,
    dbtStatus: 'Credited (100% Complete)',
    utrNumber: 'HDFCR52025041244'
  },
  {
    saleId: 'SALE-2024-PB-9012',
    cropName: 'Mustard (Sarson)',
    deliveredDate: '24 Mar 2024',
    mandiName: 'Samrala Agro Procurement Yard',
    netWeightQtl: 38.00,
    qualityGrade: 'Grade B (FAQ Standard)',
    ratePerQtl: 5650,
    totalDisbursed: 214700,
    dbtStatus: 'Credited (100% Complete)',
    utrNumber: 'PUNBR52024032488'
  }
];

// Emergency & Delay Templates for Procurement Officers
const EMERGENCY_TEMPLATES = [
  {
    id: 'tpl-rain',
    title: 'Monsoon / Heavy Rain Downpour Warning',
    severity: 'EMERGENCY', // EMERGENCY | DELAY | ADVISORY
    category: 'Weather Alert',
    delayMinutes: 45,
    message: 'Sudden rainstorm detected in Khanna Tehsil. All open-shed grain unloading is temporarily paused for 45 mins. Tarpaulin covers deployed across all bays.',
    targetAudience: 'ALL_QUEUED'
  },
  {
    id: 'tpl-scale-calib',
    title: 'Weighbridge Line #2 Sensor Calibration',
    severity: 'DELAY',
    category: 'Equipment Maintenance',
    delayMinutes: 20,
    message: 'Weighbridge Scale Line #2 is undergoing a 20-minute digital calibration test. All trucks in queue are temporarily rerouted to Line #1. Please hold positions.',
    targetAudience: 'ALL_QUEUED'
  },
  {
    id: 'tpl-gate-congestion',
    title: 'North Gate Traffic Congestion & Holding Bay Divert',
    severity: 'DELAY',
    category: 'Logistics / Traffic',
    delayMinutes: 15,
    message: 'High vehicle volume at Main Gate 1. Inward tractor-trolleys with tokens T-105 to T-120 please proceed to Eastern Holding Bay for queue staging.',
    targetAudience: 'SCHEDULED_TODAY'
  },
  {
    id: 'tpl-moisture-notice',
    title: 'FAQ Moisture Quality Protocol Advisory',
    severity: 'ADVISORY',
    category: 'Quality Testing',
    delayMinutes: 0,
    message: 'Standard Mandi FAQ moisture limit for Wheat is strictly 12.0%. Ensure lots are sun-dried before presenting at gate to avoid dockage deductions.',
    targetAudience: 'ALL_FARMERS'
  },
  {
    id: 'tpl-power-backup',
    title: 'Grid Power Switchover to Industrial Backup Generator',
    severity: 'DELAY',
    category: 'Facility Operations',
    delayMinutes: 10,
    message: 'State electricity grid voltage drop. Switching to on-site 250 kVA backup generator. Scale data terminals will resume operations in 5-10 minutes.',
    targetAudience: 'ALL_QUEUED'
  }
];

// Initial Emergency Broadcast History Records
const INITIAL_BROADCAST_HISTORY = [
  {
    id: 'ALERT-2026-0910-01',
    title: 'Morning Gate 1 Inflow Regulation',
    category: 'Logistics',
    severity: 'ADVISORY',
    message: 'Gate #1 opened on schedule. High-yield and priority fast-track lanes active on Weighbridge Counter 1.',
    dispatchedAt: 'Today, 07:30 AM',
    dispatchedBy: 'Suresh Kumar (FCI Officer #104)',
    targetAudience: 'All Queued Farmers',
    delayMinutes: 0,
    recipientsCount: 42,
    status: 'RESOLVED'
  }
];

const DICTIONARY = {
  en: {
    appTitle: 'Smart Agricultural Procurement & Slot Management',
    tagline: 'Procurement Digitization, Queue Elimination & Transparent Payouts',
    govtTagline: 'Government of India • Ministry of Agriculture & Farmers Welfare',
    selectLoginPortal: 'Please select your login portal to continue',
    farmerAccess: 'Farmer Access',
    farmerLogin: 'Farmer Login',
    farmerLoginDesc: 'Schedule crop delivery slots, view digital passes, track real-time yard queues, and monitor direct DBT bank payouts.',
    registeredMobile: 'Registered Mobile Number (10 Digits Only)',
    mobileHint: 'Numbers only (0-9). Exactly 10 digits required.',
    getOtp: 'Get OTP',
    enterOtp: 'Enter Verification OTP (6 Digits)',
    farmerId: 'Farmer ID (Optional)',
    loginFarmerBtn: 'Login as Farmer',
    officialAccess: 'Official / Yard Access',
    officialLogin: 'Official / Admin Login',
    officialLoginDesc: 'On-site gate scanner, automated weighbridge operations, quality lab testing, live yard broadcast, and enterprise monitoring.',
    employeeId: 'Official Employee ID (Max 12 Characters) *',
    mandiCenter: 'Procurement Mandi / Yard Center *',
    securityPin: 'Security PIN (Max 6 Digits) *',
    loginOfficialBtn: 'Verify & Login as Official',
    roleFarmer: 'Farmer Portal',
    roleAdmin: 'Mandi Operations & Governance',
    roleYard: 'Yard Manager',
    roleTV: 'Live Yard TV Display',
    roleEmergency: 'Emergency & Delay Console',
    roleAnalysis: 'Enterprise Analysis',
    userSettings: 'User Settings & Sales History',
    bookSlot: 'Book Agricultural Procurement Slot',
    bookSlotDesc: 'Direct-to-mandi quota allocation with automated smallholder priority reservation (≤ 100 Quintals)',
    myPasses: 'My Passes & Queues',
    payoutTracker: 'Payout Tracking',
    centerSelect: 'Select Procurement Center',
    cropSelect: 'Select Crop & Declare Quantity',
    quantity: 'Quantity (Quintals)',
    vehicleNo: 'Vehicle Registration No.',
    estPayout: 'Estimated Payout Calculation',
    prefDate: 'Select Preferred Date',
    slotSelect: 'Select Hourly Arrival Window',
    fastTrack: 'Fast-Track Available',
    priorityRule: 'Priority Rule: Smallholder lots (≤ 100 Qtl) receive fast-track weighbridge allocation to ensure under-20 minute turnaround.',
    confirmBooking: 'Confirm Booking & Generate Digital Pass with OTP',
    paymentLifecycle: '3-Space Payment & Procurement Lifecycle',
    mandiIntelligence: 'Live Mandi Procurement Intelligence & Quality Advisories',
    activePasses: 'Active Procurement Passes & Digital Tokens',
    gateScanner: 'Digital Gate Arrival Scanner & OTP Verification',
    gateScannerDesc: 'Enter Booking Reference or Gate OTP to issue live sequence token',
    checkInBtn: 'Check-In',
    liveQueuePipeline: 'Live Mandi Queue & Operations Pipeline',
    weighbridgeTerminal: 'Automated Weighbridge & Quality Testing Terminal',
    statusBooked: 'Slot Confirmed',
    statusCheckedIn: 'At Gate / Token Issued',
    statusActiveQueue: 'In Processing Queue',
    statusWeighed: 'Weighment Completed',
    statusApproved: 'Quality Approved',
    statusPaymentInitiated: 'DBT Initiated',
    statusPaymentCompleted: 'Payout Completed',
    servingNow: 'NOW SERVING',
    nextInQueue: 'NEXT IN LINE',
    estimatedWait: 'Est. Wait Time',
    currentStage: 'Current Stage',
    offlineBanner: 'Offline Mode Active. On-site weighments and gate entries are saved locally and will auto-sync when network returns.',
    logout: 'Logout',
    online: 'Online',
    offline: 'Offline',
    language: 'Language',
    featurePhone: 'Feature Phone (USSD)',
    close: 'Close',
    cancel: 'Cancel',
    emergencyNotice: 'Emergency Notice',
    broadcastHistory: 'Broadcast History'
  },
  hi: {
    appTitle: 'कृषि खरीद एवं स्लॉट प्रबंधन प्रणाली',
    tagline: 'मंडी की कतारों से मुक्ति, पारदर्शी प्रत्यक्ष बैंक भुगतान',
    govtTagline: 'भारत सरकार • कृषि एवं किसान कल्याण मंत्रालय',
    selectLoginPortal: 'कृपया आगे बढ़ने के लिए अपना लॉगिन पोर्टल चुनें',
    farmerAccess: 'किसान पोर्टल',
    farmerLogin: 'किसान लॉगिन',
    farmerLoginDesc: 'फसल वितरण स्लॉट बुक करें, डिजिटल पास देखें, लाइव कतार ट्रैक करें और सीधे डीबीटी बैंक भुगतान की निगरानी करें।',
    registeredMobile: 'पंजीकृत मोबाइल नंबर (केवल 10 अंक)',
    mobileHint: 'केवल अंक (0-9)। 10 अंक अनिवार्य हैं।',
    getOtp: 'ओटीपी प्राप्त करें',
    enterOtp: 'सत्यापन ओटीपी दर्ज करें (6 अंक)',
    farmerId: 'किसान आईडी (वैकल्पिक)',
    loginFarmerBtn: 'किसान के रूप में लॉगिन करें',
    officialAccess: 'अधिकारी / यार्ड लॉगिन',
    officialLogin: 'अधिकारी / एडमिन लॉगिन',
    officialLoginDesc: 'गेट स्कैनर, स्वचालित वेईब्रिज संचालन, गुणवत्ता जांच, लाइव यार्ड प्रसारण और डैशबोर्ड।',
    employeeId: 'अधिकारी कर्मचारी आईडी (अधिकतम 12 अक्षर) *',
    mandiCenter: 'खरीद मंडी / यार्ड केंद्र *',
    securityPin: 'सुरक्षा पिन (अधिकतम 6 अंक) *',
    loginOfficialBtn: 'सत्यापित करें और लॉगिन करें',
    roleFarmer: 'किसान पोर्टल',
    roleAdmin: 'मंडी संचालन एवं नियंत्रण',
    roleYard: 'यार्ड प्रबंधक',
    roleTV: 'लाइव टीवी डिस्प्ले',
    roleEmergency: 'आपातकालीन सूचना कंसोल',
    roleAnalysis: 'प्रशासनिक विश्लेषण',
    userSettings: 'उपयोगकर्ता सेटिंग्स एवं बिक्री इतिहास',
    bookSlot: 'नया कृषि खरीद स्लॉट बुक करें',
    bookSlotDesc: 'मंडी कोटा आवंटन और छोटे किसानों के लिए प्राथमिकता (≤ 100 क्विंटल)',
    myPasses: 'मेरे पास और कतार स्थिति',
    payoutTracker: 'भुगतान स्थिति ट्रैकर',
    centerSelect: 'खरीद केंद्र चुनें',
    cropSelect: 'फसल और मात्रा दर्ज करें',
    quantity: 'मात्रा (क्विंटल)',
    vehicleNo: 'वाहन पंजीकरण संख्या',
    estPayout: 'अनुमानित भुगतान गणना',
    prefDate: 'पसंदीदा तारीख चुनें',
    slotSelect: 'पसंदीदा समय स्लॉट चुनें',
    fastTrack: 'फास्ट-ट्रैक उपलब्ध',
    priorityRule: 'प्राथमिकता नियम: छोटे किसानों (≤ 100 क्विंटल) को 20 मिनट से कम समय में त्वरित तौल प्रदान की जाती है।',
    confirmBooking: 'पुष्टि करें और ओटीपी के साथ डिजिटल पास प्राप्त करें',
    paymentLifecycle: '3-चरणीय भुगतान एवं खरीद जीवनचक्र',
    mandiIntelligence: 'लाइव मंडी खरीद एवं गुणवत्ता परामर्श',
    activePasses: 'सक्रिय खरीद पास एवं डिजिटल टोकन',
    gateScanner: 'डिजिटल गेट आगमन स्कैनर एवं ओटीपी सत्यापन',
    gateScannerDesc: 'लाइव टोकन जारी करने के लिए पास संदर्भ या गेट ओटीपी दर्ज करें',
    checkInBtn: 'चेक-इन करें',
    liveQueuePipeline: 'लाइव मंडी कतार एवं संचालन पाइपलाइन',
    weighbridgeTerminal: 'स्वचालित वेईब्रिज एवं गुणवत्ता परीक्षण टर्मिनल',
    statusBooked: 'स्लॉट बुक हुआ',
    statusCheckedIn: 'गेट आगमन / टोकन जारी',
    statusActiveQueue: 'कतार में प्रक्रियाधीन',
    statusWeighed: 'वजन दर्ज हुआ',
    statusApproved: 'गुणवत्ता स्वीकृत',
    statusPaymentInitiated: 'डीबीटी भुगतान प्रेषित',
    statusPaymentCompleted: 'भुगतान पूर्ण',
    servingNow: 'वर्तमान में सेवारत टोकन',
    nextInQueue: 'कतार में अगले किसान',
    estimatedWait: 'अनुमानित प्रतीक्षा समय',
    currentStage: 'वर्तमान स्थिति',
    offlineBanner: 'ऑफलाइन मोड सक्रिय। प्रविष्टियां स्थानीय रूप से सुरक्षित हैं और नेटवर्क आने पर सिंक होंगी।',
    logout: 'लॉगआउट',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    language: 'भाषा',
    featurePhone: 'फीचर फोन (यूएसएसडी)',
    close: 'बंद करें',
    cancel: 'रद्द करें',
    emergencyNotice: 'आपातकालीन सूचना',
    broadcastHistory: 'प्रसारण इतिहास'
  },
  pa: {
    appTitle: 'ਖੇਤੀਬਾੜੀ ਖਰੀਦ ਅਤੇ ਸਲਾਟ ਪ੍ਰਬੰਧਨ ਪ੍ਰਣਾਲੀ',
    tagline: 'ਮੰਡੀ ਦੀਆਂ ਲੰਬੀਆਂ ਲਾਈਨਾਂ ਤੋਂ ਮੁਕਤੀ, ਸਿੱਧਾ ਖਾਤਾ ਭੁਗਤਾਨ',
    govtTagline: 'ਭਾਰਤ ਸਰਕਾਰ • ਖੇਤੀਬਾੜੀ ਅਤੇ ਕਿਸਾਨ ਭਲਾਈ ਮੰਤਰਾਲਾ',
    selectLoginPortal: 'ਕਿਰਪਾ ਕਰਕੇ ਅੱਗੇ ਵਧਣ ਲਈ ਆਪਣਾ ਲੌਗਇਨ ਪੋਰਟਲ ਚੁਣੋ',
    farmerAccess: 'ਕਿਸਾਨ ਪੋਰਟਲ',
    farmerLogin: 'ਕਿਸਾਨ ਲੌਗਇਨ',
    farmerLoginDesc: 'ਫ਼ਸਲ ਸਪੁਰਦਗੀ ਸਲਾਟ ਬੁੱਕ ਕਰੋ, ਡਿਜੀਟਲ ਪਾਸ ਵੇਖੋ, ਲਾਈਵ ਲਾਈਨ ਟ੍ਰੈਕ ਕਰੋ ਅਤੇ ਸਿੱਧੇ ਡੀਬੀਟੀ ਬੈਂਕ ਭੁਗਤਾਨ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ।',
    registeredMobile: 'ਰਜਿਸਟਰਡ ਮੋਬਾਈਲ ਨੰਬਰ (ਸਿਰਫ਼ 10 ਅੰਕ)',
    mobileHint: 'ਸਿਰਫ਼ ਅੰਕ (0-9)। 10 ਅੰਕ ਲਾਜ਼ਮੀ ਹਨ।',
    farmerId: 'ਕਿਸਾਨ ਆਈਡੀ (ਵਿਕਲਪਿਕ)',
    loginFarmerBtn: 'ਕਿਸਾਨ ਵਜੋਂ ਲੌਗਇਨ ਕਰੋ',
    officialAccess: 'ਅਧਿਕਾਰੀ / ਮੰਡੀ ਲੌਗਇਨ',
    officialLogin: 'ਅਧਿਕਾਰੀ / ਐਡਮਿਨ ਲੌਗਇਨ',
    officialLoginDesc: 'ਗੇਟ ਸਕੈਨਰ, ਕੰਪਿਊਟਰਾਈਜ਼ਡ ਕੰਡਾ, ਗੁਣਵੱਤਾ ਲੈਬ ਜਾਂਚ ਅਤੇ ਲਾਈਵ ਯਾਰਡ ਡਿਸਪਲੇ।',
    employeeId: 'ਕਰਮਚਾਰੀ ਆਈਡੀ *',
    mandiCenter: 'ਖਰੀਦ ਮੰਡੀ / ਯਾਰਡ ਸੈਂਟਰ *',
    department: 'ਵਿਭਾਗ *',
    securityPin: 'ਸੁਰੱਖਿਆ ਪਿੰਨ *',
    loginOfficialBtn: 'ਤਸਦੀਕ ਕਰੋ ਅਤੇ ਲੌਗਇਨ ਕਰੋ',
    roleFarmer: 'ਕਿਸਾਨ ਪੋਰਟਲ',
    roleAdmin: 'ਮੰਡੀ ਸੰਚਾਲਨ ਅਤੇ ਪ੍ਰਬੰਧਨ',
    roleYard: 'ਮੰਡੀ ਪ੍ਰਬੰਧਕ',
    roleTV: 'ਲਾਈਵ ਟੀਵੀ ਡਿਸਪਲੇ',
    roleEmergency: 'ਐਮਰਜੈਂਸੀ ਅਲਰਟ ਕੰਸੋਲ',
    roleAnalysis: 'ਐਂਟਰਪ੍ਰਾਈਜ਼ ਵਿਸ਼ਲੇਸ਼ਣ',
    userSettings: 'ਯੂਜ਼ਰ ਸੈਟਿੰਗਾਂ ਅਤੇ ਵਿਕਰੀ ਇਤਿਹਾਸ',
    bookSlot: 'ਨਵਾਂ ਖੇਤੀ ਖਰੀਦ ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    bookSlotDesc: 'ਛੋਟੇ ਕਿਸਾਨਾਂ ਲਈ ਪਹਿਲ ਦੇ ਆਧਾਰ ਤੇ ਸਲਾਟ ਬੁਕਿੰਗ (≤ 100 ਕੁਇੰਟਲ)',
    myPasses: 'ਮੇਰੇ ਡਿਜੀਟਲ ਪਾਸ',
    payoutTracker: 'ਭੁਗਤਾਨ ਟ੍ਰੈਕਰ',
    centerSelect: 'ਖਰੀਦ ਕੇਂਦਰ ਚੁਣੋ',
    cropSelect: 'ਫ਼ਸਲ ਅਤੇ ਮਾਤਰਾ ਦੱਸੋ',
    quantity: 'ਮਾਤਰਾ (ਕੁਇੰਟਲ)',
    vehicleNo: 'ਗੱਡੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਨੰਬਰ',
    estPayout: 'ਅੰਦਾਜ਼ਨ ਭੁਗਤਾਨ ਗਣਨਾ',
    prefDate: 'ਤਾਰੀਖ਼ ਚੁਣੋ',
    slotSelect: 'ਸਮਾਂ ਸਲਾਟ ਚੁਣੋ',
    fastTrack: 'ਫਾਸਟ-ਟਰੈਕ ਉਪਲਬਧ',
    priorityRule: 'ਪਹਿਲ ਨਿਯਮ: ਛੋਟੇ ਕਿਸਾਨਾਂ (≤ 100 ਕੁਇੰਟਲ) ਨੂੰ 20 ਮਿੰਟ ਵਿੱਚ ਤੋਲ ਦੀ ਸਹੂਲਤ।',
    confirmBooking: 'ਬੁਕਿੰਗ ਪੱਕੀ ਕਰੋ ਅਤੇ ਓਟੀਪੀ ਵਾਲਾ ਪਾਸ ਲਓ',
    paymentLifecycle: '3-ਪੜਾਵੀ ਭੁਗਤਾਨ ਅਤੇ ਖਰੀਦ ਚੱਕਰ',
    mandiIntelligence: 'ਮੰਡੀ ਖਰੀਦ ਸੂਚਨਾ ਅਤੇ ਗੁਣਵੱਤਾ ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼',
    activePasses: 'ਸਰਗਰਮ ਖਰੀਦ ਪਾਸ ਅਤੇ ਡਿਜੀਟਲ ਟੋਕਨ',
    gateScanner: 'ਗੇਟ ਆਮਦ ਸਕੈਨਰ ਅਤੇ ਓਟੀਪੀ ਤਸਦੀਕ',
    gateScannerDesc: 'ਟੋਕਨ ਜਾਰੀ ਕਰਨ ਲਈ ਪਾਸ ਰੈਫਰੈਂਸ ਜਾਂ ਓਟੀਪੀ ਦਰਜ ਕਰੋ',
    checkInBtn: 'ਚੈੱਕ-ਇਨ ਕਰੋ',
    liveQueuePipeline: 'ਲਾਈਵ ਮੰਡੀ ਕਤਾਰ ਅਤੇ ਸੰਚਾਲਨ',
    weighbridgeTerminal: 'ਕੰਪਿਊਟਰਾਈਜ਼ਡ ਕੰਡਾ ਅਤੇ ਲੈਬ ਜਾਂਚ ਟਰਮੀਨਲ',
    statusBooked: 'ਸਲਾਟ ਬੁੱਕ ਹੋਇਆ',
    statusCheckedIn: 'ਗੇਟ ਤੇ ਆਮਦ ਦਰਜ',
    statusActiveQueue: 'ਪ੍ਰੋਸੈਸਿੰਗ ਕਤਾਰ ਵਿੱਚ',
    statusWeighed: 'ਤੋਲ ਮੁਕੰਮਲ',
    statusApproved: 'ਗੁਣਵੱਤਾ ਪ੍ਰਵਾਨਿਤ',
    statusPaymentInitiated: 'DBT ਭੁਗਤਾਨ ਸ਼ੁਰੂ',
    statusPaymentCompleted: 'ਖਾਤੇ ਵਿੱਚ ਰਕਮ ਜਮ੍ਹਾਂ',
    servingNow: 'ਹੁਣ ਸੇਵਾ ਦਿੱਤੀ ਜਾ ਰਹੀ ਹੈ',
    nextInQueue: 'ਕਤਾਰ ਵਿੱਚ ਅਗਲੇ',
    estimatedWait: 'ਅੰਦਾਜ਼ਨ ਉਡੀਕ ਸਮਾਂ',
    currentStage: 'ਮੌਜੂਦਾ ਸਥਿਤੀ',
    offlineBanner: 'ਆਫਲਾਈਨ ਮੋਡ ਸਰਗਰਮ ਹੈ। ਇੰਦਰਾਜ਼ ਸਥਾਨਕ ਤੌਰ ਤੇ ਸੁਰੱਖਿਅਤ ਹਨ।',
    logout: 'ਲੌਗਆਊਟ',
    online: 'ਆਨਲਾਈਨ',
    offline: 'ਆਫਲਾਈਨ',
    language: 'ਭਾਸ਼ਾ',
    featurePhone: 'ਫੀਚਰ ਫੋਨ (USSD)',
    close: 'ਬੰਦ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    emergencyNotice: 'ਐਮਰਜੈਂਸੀ ਨੋਟਿਸ',
    broadcastHistory: 'ਪ੍ਰਸਾਰਣ ਇਤਿਹਾਸ'
  },
  te: {
    appTitle: 'వ్యవసాయ సేకరణ & స్లాట్ నిర్వహణ వేదిక',
    tagline: 'మార్కెట్ యార్డ్ రద్దీ నివారణ, పారదర్శక ప్రత్యక్ష నగదు బదిలీ',
    govtTagline: 'భారత ప్రభుత్వం • వ్యవసాయ మరియు రైతు సంక్షేమ మంత్రిత్వ శాఖ',
    selectLoginPortal: 'కొనసాగడానికి దయచేసి మీ లాగిన్ పోర్టల్‌ను ఎంచుకోండి',
    farmerAccess: 'రైతు పోర్టల్',
    farmerLogin: 'రైతు లాగిన్',
    farmerLoginDesc: 'పంట డెలివరీ స్లాట్‌లను బుక్ చేయండి, డిజిటల్ పాస్‌లను చూడండి మరియు ప్రత్యక్ష డీబీటీ చెల్లింపులను పర్యవేక్షించండి.',
    registeredMobile: 'నమోదిత మొబైల్ నంబర్ (10 అంకెలు మాత్రమే)',
    mobileHint: 'అంకెలు మాత్రమే (0-9). ఖచ్చితంగా 10 అంకెలు ఉండాలి.',
    farmerId: 'రైతు ఐడీ (ఐచ్ఛికం)',
    loginFarmerBtn: 'రైతుగా లాగిన్ అవ్వండి',
    officialAccess: 'అధికారుల / యార్డ్ లాగిన్',
    officialLogin: 'అధికారుల / అడ్మిన్ లాగిన్',
    officialLoginDesc: 'గేట్ స్కానర్, ఆటోమేటెడ్ వేబ్రిడ్జ్, క్వాలిటీ టెస్టింగ్ మరియు లైవ్ యార్డ్ డిస్ప్లే.',
    employeeId: 'ఉద్యోగి ఐడీ *',
    mandiCenter: 'సేకరణ మార్కెట్ యార్డ్ *',
    department: 'విభాగం *',
    securityPin: 'భద్రతా పిన్ *',
    loginOfficialBtn: 'ధృవీకరించి లాగిన్ అవ్వండి',
    roleFarmer: 'రైతు పోర్టల్',
    roleAdmin: 'మార్కెట్ యార్డ్ కార్యకలాపాలు & నిర్వహణ',
    roleYard: 'యార్డ్ మేనేజర్',
    roleTV: 'లైవ్ టీవీ డిస్ప్లే',
    roleEmergency: 'అత్యవసర సమాచార కన్సోల్',
    roleAnalysis: 'విశ్లేషణలు',
    userSettings: 'యూజర్ సెట్టింగ్‌లు & అమ్మకాల చరిత్ర',
    bookSlot: 'వ్యవసాయ సేకరణ స్లాట్‌ను బుక్ చేయండి',
    bookSlotDesc: 'చిన్న రైతులకు ప్రాధాన్యతతో కూడిన స్లాట్ కేటాయింపు (≤ 100 క్వింటాళ్లు)',
    myPasses: 'నా పాస్‌లు & క్యూ స్థితి',
    payoutTracker: 'చెల్లింపుల ట్రాకింగ్',
    centerSelect: 'సేకరణ కేంద్రాన్ని ఎంచుకోండి',
    cropSelect: 'పంట & పరిమాణం నమోదు చేయండి',
    quantity: 'పరిమాణం (క్వింటాళ్లలో)',
    vehicleNo: 'వాహన రిజిస్ట్రేషన్ సంఖ్య',
    estPayout: 'అంచనా వేసిన చెల్లింపు గణన',
    prefDate: 'తేదీని ఎంచుకోండి',
    slotSelect: 'స్లాట్ సమయం ఎంచుకోండి',
    fastTrack: 'ఫాస్ట్-ట్రాక్ అందుబాటులో ఉంది',
    priorityRule: 'ప్రాధాన్యత నిబంధన: చిన్న రైతులకు (≤ 100 క్వింటాళ్లు) 20 నిమిషాలలోపు తూకం సదుపాయం.',
    confirmBooking: 'బుకింగ్ నిర్ధారించి ఓటీపీ పాస్ పొందండి',
    paymentLifecycle: '3-దశల చెల్లింపు & సేకరణ ప్రక్రియ',
    mandiIntelligence: 'లైవ్ మార్కెట్ యార్డ్ సమాచారం & నాణ్యత సూచనలు',
    activePasses: 'యాక్టివ్ సేకరణ పాస్‌లు & డిజిటల్ టోకెన్లు',
    gateScanner: 'గేట్ వద్ద స్కానర్ & ఓటీపీ ధృవీకరణ',
    gateScannerDesc: 'లైవ్ టోకెన్ జారీ చేయడానికి పాస్ రిఫరెన్స్ లేదా ఓటీపీ నమోదు చేయండి',
    checkInBtn: 'చెక్-ఇన్',
    liveQueuePipeline: 'లైవ్ క్యూ & కార్యకలాపాల పైప్‌లైన్',
    weighbridgeTerminal: 'ఆటోమేటెడ్ వేబ్రిడ్జ్ & క్వాలిటీ ల్యాబ్ టెర్మినల్',
    statusBooked: 'స్లాట్ ఖరారైంది',
    statusCheckedIn: 'గేట్ వద్దకు చేరారు',
    statusActiveQueue: 'క్యూలో ఉంది',
    statusWeighed: 'తూకం పూర్తయింది',
    statusApproved: 'నాణ్యత ఆమోదించబడింది',
    statusPaymentInitiated: 'డీబీటీ చెల్లింపు ప్రారంభమైంది',
    statusPaymentCompleted: 'ఖాతాలో జమయింది',
    servingNow: 'ప్రస్తుతం సేవలందిస్తున్న టోకెన్',
    nextInQueue: 'తదుపరి టోకెన్లు',
    estimatedWait: 'వేచి ఉండే సమయం',
    currentStage: 'ప్రస్తుత దశ',
    offlineBanner: 'ఆఫ్‌లైన్ మోడ్ యాక్టివ్‌గా ఉంది. వివరాలు స్థానికంగా సేవ్ చేయబడతాయి.',
    logout: 'లాగౌట్',
    online: 'ఆన్‌లైన్',
    offline: 'ఆఫ్‌లైన్',
    language: 'భాష',
    featurePhone: 'ఫీచర్ ఫోన్ (USSD)',
    close: 'మూసివేయి',
    cancel: 'రద్దు చేయి',
    emergencyNotice: 'అత్యవసర ప్రకటన',
    broadcastHistory: 'ప్రసార చరిత్ర'
  },
  ta: {
    appTitle: 'வேளாண் கொள்முதல் மற்றும் நேர முன்பதிவு தளம்',
    tagline: 'மண்டி வரிசை நீக்கம், வெளிப்படையான நேரடி வங்கிப் பரிமாற்றம்',
    govtTagline: 'இந்திய அரசு • வேளாண்மை மற்றும் உழவர் நலத்துறை அமைச்சகம்',
    selectLoginPortal: 'தொடர உங்கள் உள்நுழைவு போர்ட்டலைத் தேர்ந்தெடுக்கவும்',
    farmerAccess: 'விவசாயிகள் பகுதி',
    farmerLogin: 'விவசாயி உள்நுழைவு',
    farmerLoginDesc: 'பயிர் வழங்கல் முன்பதிவு, டிஜிட்டல் பாஸ், நேரலை வரிசை கண்காணிப்பு மற்றும் நேரடி வங்கி வரவு.',
    registeredMobile: 'பதிவு செய்யப்பட்ட மொபைல் எண் (10 இலக்கங்கள்)',
    mobileHint: 'எண்கள் மட்டும் (0-9). சரியாக 10 இலக்கங்கள் தேவை.',
    farmerId: 'விவசாயி அடையாள எண் (விருப்பத்தேர்வு)',
    loginFarmerBtn: 'விவசாயியாக உள்நுழைக',
    officialAccess: 'அதிகாரிகள் பகுதி',
    officialLogin: 'அதிகாரி / நிர்வாகி உள்நுழைவு',
    officialLoginDesc: 'நுழைவு வாயில் ஸ்கேனர், தானியங்கி எடையிடும் கருவி, தரப் பரிசோதனை மற்றும் நேரலை பலகை.',
    employeeId: 'பணியாளர் ஐடி *',
    mandiCenter: 'கொள்முதல் மண்டி மையம் *',
    department: 'துறை *',
    securityPin: 'பாதுகாப்பு பின் *',
    loginOfficialBtn: 'சரிபார்த்து உள்நுழைக',
    roleFarmer: 'விவசாயிகள் தளம்',
    roleAdmin: 'மண்டி மேலாண்மை & நிர்வாகம்',
    roleYard: 'மண்டி மேலாளர்',
    roleTV: 'நேரலை டிவி காட்சி',
    roleEmergency: 'அவசர அறிவிப்பு மையம்',
    roleAnalysis: 'நிறுவன பகுப்பாய்வு',
    userSettings: 'பயனர் அமைப்புகள் & விற்பனை வரலாறு',
    bookSlot: 'விவசாய கொள்முதல் நேரத்தை முன்பதிவு செய்க',
    bookSlotDesc: 'சிறு விவசாயிகளுக்கான முன்னுரிமை ஒதுக்கீடு (≤ 100 குவிண்டால்)',
    myPasses: 'எனது பாஸ்கள் & வரிசை',
    payoutTracker: 'பணப்பரிவர்த்தனை கண்காணிப்பு',
    centerSelect: 'கொள்முதல் மையத்தைத் தேர்ந்தெடுக்கவும்',
    cropSelect: 'பயிர் மற்றும் அளவை உள்ளிடவும்',
    quantity: 'அளவு (குவிண்டால்)',
    vehicleNo: 'வாகனப் பதிவு எண்',
    estPayout: 'மதிப்பிடப்பட்ட தொகை கணக்கீடு',
    prefDate: 'தேதியைத் தேர்ந்தெடுக்கவும்',
    slotSelect: 'நேர ஸ்லாட்டைத் தேர்ந்தெடுக்கவும்',
    fastTrack: 'விரைவுப் பாதை உள்ளது',
    priorityRule: 'முன்னுரிமை விதி: சிறு விவசாயிகளுக்கு (≤ 100 குவிண்டால்) 20 நிமிடங்களுக்குள் எடை போடும் வசதி.',
    confirmBooking: 'முன்பதிவை உறுதிசெய்து OTP பாஸைப் பெறுக',
    paymentLifecycle: '3-படிநிலை கொள்முதல் மற்றும் பணப்பரிமாற்ற சுழற்சி',
    mandiIntelligence: 'மண்டி கொள்முதல் வழிகாட்டுதல்கள் மற்றும் தரம்',
    activePasses: 'செயலில் உள்ள கொள்முதல் பாஸ்கள் & டோக்கன்கள்',
    gateScanner: 'நுழைவு வாயில் ஸ்கேனர் மற்றும் OTP சரிபார்ப்பு',
    gateScannerDesc: 'டோக்கன் பெற பாஸ் எண் அல்லது OTP ஐ உள்ளிடவும்',
    checkInBtn: 'செக்-இன்',
    liveQueuePipeline: 'நேரலை வரிசை மற்றும் செயல்பாடுகள்',
    weighbridgeTerminal: 'தானியங்கி எடைமேடை & தர ஆய்வகம்',
    statusBooked: 'முன்பதிவு உறுதியானது',
    statusCheckedIn: 'நுழைவு வாயில் வரவு பதிவு',
    statusActiveQueue: 'வரிசையில் உள்ளது',
    statusWeighed: 'எடை பதிவு செய்யப்பட்டது',
    statusApproved: 'தரம் அங்கீகரிக்கப்பட்டது',
    statusPaymentInitiated: 'DBT பணப்பரிமாற்றம் தொடங்கியது',
    statusPaymentCompleted: 'பணம் வங்கியில் செலுத்தப்பட்டது',
    servingNow: 'தற்போது அழைக்கப்படும் டோக்கன்',
    nextInQueue: 'அடுத்து வரிசையில் உள்ளவர்கள்',
    estimatedWait: 'எதிர்பார்க்கப்படும் காத்திருப்பு நேரம்',
    currentStage: 'தற்போதைய நிலை',
    offlineBanner: 'ஆஃப்லைன் முறை செயலில் உள்ளது. பதிவுகள் தானாக ஒத்திசைக்கப்படும்.',
    logout: 'வெளியேறு',
    online: 'ஆன்லைன்',
    offline: 'ஆஃப்லைன்',
    language: 'மொழி',
    featurePhone: 'பீச்சர் போன் (USSD)',
    close: 'மூடு',
    cancel: 'ரத்து செய்',
    emergencyNotice: 'அவசர அறிவிப்பு',
    broadcastHistory: 'ஒளிபரப்பு வரலாறு'
  },
  bn: {
    appTitle: 'স্মার্ট কৃষি ক্রয় ও স্লট ব্যবস্থাপনা পোর্টাল',
    tagline: 'মান্ডির ভিড় নিরসন ও সরাসরি ব্যাংক একাউন্টে স্বচ্ছ অর্থপ্রদান',
    govtTagline: 'ভারত সরকার • কৃষি ও কৃষক কল্যাণ মন্ত্রক',
    selectLoginPortal: 'অনুগ্রহ করে এগিয়ে যেতে আপনার লগইন পোর্টাল নির্বাচন করুন',
    farmerAccess: 'কৃষক পোর্টাল',
    farmerLogin: 'কৃষক লগইন',
    farmerLoginDesc: 'ফসল বিক্রির স্লট বুক করুন, ডিজিটাল পাস দেখুন এবং সরাসরি ডিবিটি ব্যাংক পেমেন্ট ট্র্যাক করুন।',
    registeredMobile: 'নিবন্ধিত মোবাইল নম্বর (১০ সংখ্যার)',
    mobileHint: 'শুধুমাত্র সংখ্যা (০-৯)। ঠিক ১০টি সংখ্যা আবশ্যক।',
    farmerId: 'কৃষক আইডি (ঐচ্ছিক)',
    loginFarmerBtn: 'কৃষক হিসেবে লগইন করুন',
    officialAccess: 'আধিকারিক লগইন',
    officialLogin: 'অফিসিয়াল / অ্যাডমিন লগইন',
    officialLoginDesc: 'গেট স্ক্যানার, স্বয়ংক্রিয় ওজন মাপার স্কেল, গুণমান পরীক্ষা এবং লাইভ ডিসপ্লে।',
    employeeId: 'কর্মচারী আইডি *',
    mandiCenter: 'ক্রয় কেন্দ্র / মান্ডি *',
    department: 'বিভাগ *',
    securityPin: 'নিরাপত্তা পিন *',
    loginOfficialBtn: 'যাচাই করুন এবং লগইন করুন',
    roleFarmer: 'কৃষক পোর্টাল',
    roleAdmin: 'মান্ডি পরিচালনা ও প্রশাসন',
    roleYard: 'ইয়ার্ড ম্যানেজার',
    roleTV: 'লাইভ টিভি ডিসপ্লে',
    roleEmergency: 'জরুরি সতর্কতা কনসোল',
    roleAnalysis: 'বিশ্লেষণ',
    userSettings: 'ইউজার সেটিংস ও বিক্রির ইতিহাস',
    bookSlot: 'কৃষি ক্রয় স্লট বুক করুন',
    bookSlotDesc: 'ক্ষুদ্র কৃষকদের জন্য অগ্রাধিকার ভিত্তিক স্লট বণ্টন (≤ ১০০ কুইন্টাল)',
    myPasses: 'আমার ডিজিটাল পাস ও সারি',
    payoutTracker: 'পেমেন্ট ট্র্যাকিং',
    centerSelect: 'ক্রয় কেন্দ্র নির্বাচন করুন',
    cropSelect: 'ফসল ও পরিমাণ লিখুন',
    quantity: 'পরিমাণ (কুইন্টাল)',
    vehicleNo: 'যানবাহন নিবন্ধন নম্বর',
    estPayout: 'আনুমানিক মূল্য হিসাব',
    prefDate: 'তারিখ নির্বাচন করুন',
    slotSelect: 'সময় স্লট নির্বাচন করুন',
    fastTrack: 'দ্রুত সেবা উপলব্ধ',
    priorityRule: 'অগ্রাধিকার নিয়ম: ক্ষুদ্র কৃষকদের (≤ ১০০ কুইন্টাল) ২০ মিনিটের মধ্যে ওজন সুবিধা।',
    confirmBooking: 'বুকিং নিশ্চিত করুন এবং OTP পাস পান',
    paymentLifecycle: '৩-ধাপের ক্রয় ও অর্থপ্রদান প্রক্রিয়া',
    mandiIntelligence: 'লাইভ মান্ডি তথ্য ও গুণমান নির্দেশিকা',
    activePasses: 'সক্রিয় ডিজিটাল পাস ও টোকেন',
    gateScanner: 'গেট স্ক্যানার ও OTP যাচাইকরণ',
    gateScannerDesc: 'টোকেন পেতে পাস নম্বর বা OTP লিখুন',
    checkInBtn: 'চেক-ইন',
    liveQueuePipeline: 'লাইভ মান্ডি সারি ও কার্যক্রম',
    weighbridgeTerminal: 'স্বয়ংক্রিয় ওজন মাপার টার্মিনাল',
    statusBooked: 'স্লট বুক হয়েছে',
    statusCheckedIn: 'গেটে আগমন সম্পন্ন',
    statusActiveQueue: 'সারিতে অপেক্ষমাণ',
    statusWeighed: 'ওজন সম্পন্ন',
    statusApproved: 'গুণমান অনুমোদিত',
    statusPaymentInitiated: 'DBT পেমেন্ট শুরু',
    statusPaymentCompleted: 'টাকা অ্যাকাউন্টে জমা হয়েছে',
    servingNow: 'বর্তমান পরিবেশিত টোকেন',
    nextInQueue: 'সারিতে পরবর্তী কৃষক',
    estimatedWait: 'আনুমানিক অপেক্ষার সময়',
    currentStage: 'বর্তমান অবস্থা',
    offlineBanner: 'অফলাইন মোড সক্রিয়। তথ্য নেটওয়ার্ক ফিরলে স্বয়ংক্রিয়ভাবে সিঙ্ক হবে।',
    logout: 'লগআউট',
    online: 'অনলাইন',
    offline: 'অফলাইন',
    language: 'ভাষা',
    featurePhone: 'ফিচার ফোন (USSD)',
    close: 'বন্ধ করুন',
    cancel: 'বাতিল করুন',
    emergencyNotice: 'জরুরি বিজ্ঞপ্তি',
    broadcastHistory: 'বিজ্ঞপ্তি ইতিহাস'
  },
  mr: {
    appTitle: 'स्मार्ट कृषी खरेदी व स्लॉट व्यवस्थापन प्रणाली',
    tagline: 'बाजार समितीतील रांगांमधून मुक्ती, थेट बँक खात्यात पारदर्शक रक्कम',
    govtTagline: 'भारत सरकार • कृषी आणि शेतकरी कल्याण मंत्रालय',
    selectLoginPortal: 'कृपया पुढे जाण्यासाठी आपले लॉगिन पोर्टल निवडा',
    farmerAccess: 'शेतकरी पोर्टल',
    farmerLogin: 'शेतकरी लॉगिन',
    farmerLoginDesc: 'शेतमाल विक्री स्लॉट बुक करा, डिजिटल पास पहा, लाईव्ह रांग ट्रॅक करा आणि थेट डीबीटी बँक जमा तपासा.',
    registeredMobile: 'नोंदणीकृत मोबाईल क्रमांक (१० अंक)',
    mobileHint: 'केवळ अंक (०-९). अचूक १० अंक आवश्यक आहेत.',
    farmerId: 'शेतकरी आयडी (पर्यायी)',
    loginFarmerBtn: 'शेतकरी म्हणून लॉगिन करा',
    officialAccess: 'अधिकारी / यार्ड लॉगिन',
    officialLogin: 'अधिकारी / प्रशासन लॉगिन',
    officialLoginDesc: 'गेट स्कॅनर, डिजिटल वजनकाटा, गुणवत्ता तपासणी प्रयोगशाळा आणि थेट यार्ड प्रदर्शन.',
    employeeId: 'कर्मचारी आयडी *',
    mandiCenter: 'खरेदी केंद्र / कृषी उत्पन्न बाजार समिती *',
    department: 'विभाग *',
    securityPin: 'सुरक्षा पिन *',
    loginOfficialBtn: 'पडताळणी करा आणि लॉगिन करा',
    roleFarmer: 'शेतकरी पोर्टल',
    roleAdmin: 'बाजार समिती कामकाज व नियंत्रण',
    roleYard: 'यार्ड व्यवस्थापक',
    roleTV: 'लाईव्ह टीव्ही डिस्प्ले',
    roleEmergency: 'तातडीची सूचना प्रणाली',
    roleAnalysis: 'प्रशासकीय विश्लेषण',
    userSettings: 'वापरकर्ता सेटिंग्ज आणि विक्री इतिहास',
    bookSlot: 'कृषी खरेदी स्लॉट बुक करा',
    bookSlotDesc: 'अल्पभूधारक शेतकऱ्यांसाठी प्राधान्य स्लॉट वाटप (≤ १०० क्विंटल)',
    myPasses: 'माझे डिजिटल पास व रांग',
    payoutTracker: 'पेमेंट ट्रॅकिंग',
    centerSelect: 'खरेदी केंद्र निवडा',
    cropSelect: 'पीक आणि प्रमाण निवडा',
    quantity: 'प्रमाण (क्विंटल)',
    vehicleNo: 'वाहन नोंदणी क्रमांक',
    estPayout: 'अंदाजे रक्कम गणना',
    prefDate: 'तारीख निवडा',
    slotSelect: 'वेळ स्लॉट निवडा',
    fastTrack: 'जलद सेवा उपलब्ध',
    priorityRule: 'प्राधान्य नियम: अल्पभूधारक शेतकऱ्यांना (≤ १०० क्विंटल) २० मिनिटांत वजन सुविधा.',
    confirmBooking: 'नोंदणी निश्चित करा आणि ओटीपी पास मिळवा',
    paymentLifecycle: '३-टप्प्यांची खरेदी आणि थेट पेमेंट प्रक्रिया',
    mandiIntelligence: 'बाजार समिती थेट माहिती व गुणवत्ता सल्ला',
    activePasses: 'सक्रिय डिजिटल पास आणि टोकन',
    gateScanner: 'गेट आगमन स्कॅनर आणि ओटीपी पडताळणी',
    gateScannerDesc: 'टोकन मिळवण्यासाठी पास क्रमांक किंवा ओटीपी प्रविष्ट करा',
    checkInBtn: 'चेक-इन करा',
    liveQueuePipeline: 'लाईव्ह रांग व यार्ड कामकाज',
    weighbridgeTerminal: 'स्वयंचलित वजनकाटा व लॅब टर्मिनल',
    statusBooked: 'स्लॉट निश्चित झाला',
    statusCheckedIn: 'गेटवर आगमन नोंदवले',
    statusActiveQueue: 'प्रक्रियेत आहे',
    statusWeighed: 'वजन पूर्ण झाले',
    statusApproved: 'गुणवत्ता मंजूर',
    statusPaymentInitiated: 'डीबीटी सुरू केले',
    statusPaymentCompleted: 'रक्कम खात्यात जमा झाली',
    servingNow: 'सध्या सेवेत असलेले टोकन',
    nextInQueue: 'रांगेत पुढील शेतकरी',
    estimatedWait: 'अंदाजे प्रतीक्षा वेळ',
    currentStage: 'सद्यस्थिती',
    offlineBanner: 'ऑफलाईन मोड सुरू आहे. नोंदी स्थानिकरीत्या जतन केल्या जातील.',
    logout: 'लॉगआउट',
    online: 'ऑनलाईन',
    offline: 'ऑफलाईन',
    language: 'भाषा',
    featurePhone: 'साधा फोन (USSD)',
    close: 'बंद करा',
    cancel: 'रद्द करा',
    emergencyNotice: 'तातडीची सूचना',
    broadcastHistory: 'सूचना इतिहास'
  },
  gu: {
    appTitle: 'સ્માર્ટ કૃષિ ખરીદ અને સ્લોટ મેનેજમેન્ટ પ્લેટફોર્મ',
    tagline: 'માર્કેટ યાર્ડની લાઈનોમાંથી મુક્તિ, પારદર્શક સીધું બેંક ખાતામાં ચુકવણું',
    govtTagline: 'ભારત સરકાર • કૃષિ અને ખેડૂત કલ્યાણ મંત્રાલય',
    selectLoginPortal: 'કૃપા કરીને આગળ વધવા માટે તમારું લૉગિન પોર્ટલ પસંદ કરો',
    farmerAccess: 'ખેડૂત પોર્ટલ',
    farmerLogin: 'ખેડૂત લૉગિન',
    farmerLoginDesc: 'પાક વેચાણ સ્લોટ બુક કરો, ડિજિટલ પાસ જુઓ અને સીધા ડીબીટી પેમેન્ટ ટ્રેક કરો.',
    registeredMobile: 'નોંધાયેલ મોબાઈલ નંબર (૧૦ અંક)',
    mobileHint: 'માત્ર અંકો (૦-૯). બરાબર ૧૦ અંક જરૂરી છે.',
    farmerId: 'ખેડૂત આઈડી (વૈકલ્પિક)',
    loginFarmerBtn: 'ખેડૂત તરીકે લૉગિન કરો',
    officialAccess: 'અધિકારી લૉગિન',
    officialLogin: 'અધિકારી / એડમિન લૉગિન',
    officialLoginDesc: 'ગેટ સ્કેનર, ઓટોમેટિક વેઈબ્રિજ, ગુણવત્તા ચકાસણી અને લાઈવ ડિસ્પ્લે.',
    employeeId: 'કર્મચારી આઈડી *',
    mandiCenter: 'ખરીદ કેન્દ્ર / યાર્ડ *',
    department: 'વિભાગ *',
    securityPin: 'સિક્યોરિટી પિન *',
    loginOfficialBtn: 'ચકાસો અને લૉગિન કરો',
    roleFarmer: 'ખેડૂત પોર્ટલ',
    roleAdmin: 'યાર્ડ વહીવટ અને સંચાલન',
    roleYard: 'યાર્ડ મેનેજર',
    roleTV: 'લાઈવ ટીવી ડિસ્પ્લે',
    roleEmergency: 'કટોકટી ચેતવણી કન્સોલ',
    roleAnalysis: 'વિશ્લેષણ',
    userSettings: 'યુઝર સેટિંગ્સ અને વેચાણ ઇતિહાસ',
    bookSlot: 'કૃષિ ખરીદ સ્લોટ બુક કરો',
    bookSlotDesc: 'નાના ખેડૂતો માટે અગ્રતા આધારિત સ્લોટ ફાળવણી (≤ ૧૦૦ ક્વિન્ટલ)',
    myPasses: 'મારા ડિજિટલ પાસ',
    payoutTracker: 'ચુકવણી ટ્રેકિંગ',
    centerSelect: 'ખરીદ કેન્દ્ર પસંદ કરો',
    cropSelect: 'પાક અને જથ્થો દાખલ કરો',
    quantity: 'જથ્થો (ક્વિન્ટલ)',
    vehicleNo: 'વાહન નંબર',
    estPayout: 'અંદાજિત રકમ ગણતરી',
    prefDate: 'તારીખ પસંદ કરો',
    slotSelect: 'સમય સ્લોટ પસંદ કરો',
    fastTrack: 'ઝડપી સેવા ઉપલબ્ધ',
    priorityRule: 'અગ્રતા નિયમ: નાના ખેડૂતોને (≤ ૧૦૦ ક્વિન્ટલ) ૨૦ મિનિટમાં વજનની સુવિધા.',
    confirmBooking: 'બુકિંગ કન્ફર્મ કરો અને OTP પાસ મેળવો',
    paymentLifecycle: '૩-તબક્કાની ખરીદી અને ચુકવણી પ્રક્રિયા',
    mandiIntelligence: 'યાર્ડ ખરીદી માહિતી અને ગુણવત્તા માર્ગદર્શિકા',
    activePasses: 'સક્રિય ડિજિટલ પાસ અને ટોકન',
    gateScanner: 'ગેટ સ્કેનર અને OTP ચકાસણી',
    gateScannerDesc: 'ટોકન મેળવવા પાસ નંબર અથવા OTP દાખલ કરો',
    checkInBtn: 'ચેક-ઇન',
    liveQueuePipeline: 'લાઈવ કતાર અને સંચાલન',
    weighbridgeTerminal: 'ઓટોમેટેડ વેઈબ્રિજ ટર્મિનલ',
    statusBooked: 'સ્લોટ બુક થયો',
    statusCheckedIn: 'ગેટ પર આગમન નોંધાયું',
    statusActiveQueue: 'કતારમાં પ્રક્રિયા હેઠળ',
    statusWeighed: 'વજન પૂર્ણ થયું',
    statusApproved: 'ગુણવત્તા મંજૂર',
    statusPaymentInitiated: 'DBT ચુકવણી શરૂ',
    statusPaymentCompleted: 'રકમ ખાતામાં જમા થઈ',
    servingNow: 'હાલમાં સેવા આપતું ટોકન',
    nextInQueue: 'કતારમાં આગામી ખેડૂતો',
    estimatedWait: 'અંદાજિત પ્રતીક્ષા સમય',
    currentStage: 'હાલની સ્થિતિ',
    offlineBanner: 'ઓફલાઈન મોડ સક્રિય છે. માહિતી નેટવર્ક આવ્યે આપોઆપ સિંક થશે.',
    logout: 'લૉગઆઉਟ',
    online: 'ઓનલાઈન',
    offline: 'ઓફલાઈન',
    language: 'ભાષા',
    featurePhone: 'સાદો ફોન (USSD)',
    close: 'બંધ કરો',
    cancel: 'રદ કરો',
    emergencyNotice: 'કટોકટી સૂચના',
    broadcastHistory: 'પ્રસારણ ઇતિહાસ'
  },
  kn: {
    appTitle: 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಖರೀದಿ ಮತ್ತು ಸ್ಲಾಟ್ ನಿರ್ವಹಣಾ ವೇದಿಕೆ',
    tagline: 'ಮಂಡಿ ಸಾಲುಗಳಿಂದ ಮುಕ್ತಿ, ನೇರ ಡಿಬಿಟಿ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಪಾರದರ್ಶಕ ಪಾವತಿ',
    govtTagline: 'ಭಾರತ ಸರ್ಕಾರ • ಕೃಷಿ ಮತ್ತು ರೈತರ ಕಲ್ಯಾಣ ಸಚಿವಾಲಯ',
    selectLoginPortal: 'ಮುಂದುವರಿಯಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ಲಾಗಿನ್ ಪೋರ್ಟಲ್ ಆಯ್ಕೆಮಾಡಿ',
    farmerAccess: 'ರೈತ ಪೋರ್ಟಲ್',
    farmerLogin: 'ರೈತ ಲಾಗಿನ್',
    farmerLoginDesc: 'ಬೆಳೆ ವಿತರಣಾ ಸ್ಲಾಟ್‌ಗಳನ್ನು ಕಾಯ್ದಿರಿಸಿ, ಡಿಜಿಟಲ್ ಪಾಸ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ ಮತ್ತು ನೇರ ಡಿಬಿಟಿ ಪಾವತಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
    registeredMobile: 'ನೋಂದಾಯಿತ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ (೧೦ ಅಂಕಿಗಳು)',
    mobileHint: 'ಅಂಕಿಗಳು ಮಾತ್ರ (೦-೯). ನಿಖರವಾಗಿ ೧೦ ಅಂಕಿಗಳು ಬೇಕು.',
    farmerId: 'ರೈತ ಐಡಿ (ಐಚ್ಛಿಕ)',
    loginFarmerBtn: 'ರೈತರಾಗಿ ಲಾಗಿನ್ ಮಾಡಿ',
    officialAccess: 'ಅಧಿಕಾರಿಗಳ ಲಾಗಿನ್',
    officialLogin: 'ಅಧಿಕಾರಿ / ನಿರ್ವಾಹಕ ಲಾಗಿನ್',
    officialLoginDesc: 'ಗೇಟ್ ಸ್ಕ್ಯಾನರ್, ಸ್ವಯಂಚಾಲಿತ ತೂಕದ ಯಂತ್ರ, ಗುಣಮಟ್ಟ ಪರೀಕ್ಷಾ ಪ್ರಯೋಗಾಲಯ ಮತ್ತು ಲೈವ್ ಡಿಸ್ಪ್ಲೇ.',
    employeeId: 'ಉದ್ಯೋಗಿ ಐಡಿ *',
    mandiCenter: 'ಖರೀದಿ ಮಂಡಿ / ಯಾರ್ಡ್ *',
    department: 'ಇಲಾಖೆ *',
    securityPin: 'ಭದ್ರತಾ ಪಿನ್ *',
    loginOfficialBtn: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್ ಮಾಡಿ',
    roleFarmer: 'ರೈತ ಪೋರ್ಟಲ್',
    roleAdmin: 'ಮಂಡಿ ಕಾರ್ಯಾಚರಣೆ ಮತ್ತು ಆಡಳಿತ',
    roleYard: 'ಯಾರ್ಡ್ ಮ್ಯಾನೇಜರ್',
    roleTV: 'ಲೈವ್ ಟಿವಿ ಡಿಸ್ಪ್ಲೇ',
    roleEmergency: 'ತುರ್ತು ಎಚ್ಚರಿಕೆ ಕನ್ಸೋಲ್',
    roleAnalysis: 'ವಿಶ್ಲೇಷಣೆ',
    userSettings: 'ಬಳಕೆದಾರರ ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಮಾರಾಟ ಇತಿಹಾಸ',
    bookSlot: 'ಕೃಷಿ ಖರೀದಿ ಸ್ಲಾಟ್ ಕಾಯ್ದಿರಿಸಿ',
    bookSlotDesc: 'ಸಣ್ಣ ರೈತರಿಗೆ ಆದ್ಯತೆಯ ಸ್ಲಾಟ್ ಹಂಚಿಕೆ (≤ ೧೦೦ ಕ್ವಿಂಟಾಲ್)',
    myPasses: 'ನನ್ನ ಡಿಜಿಟಲ್ ಪಾಸ್‌ಗಳು',
    payoutTracker: 'ಪಾವತಿ ಟ್ರ್ಯಾಕಿಂಗ್',
    centerSelect: 'ಖರೀದಿ ಕೇಂದ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    cropSelect: 'ಬೆಳೆ ಮತ್ತು ಪ್ರಮಾಣವನ್ನು ನಮೂದಿಸಿ',
    quantity: 'ಪ್ರಮಾಣ (ಕ್ವಿಂಟಾಲ್)',
    vehicleNo: 'ವಾಹನ ನೋಂದಣಿ ಸಂಖ್ಯೆ',
    estPayout: 'ಅಂದಾಜು ಪಾವತಿ ಲೆಕ್ಕಾಚಾರ',
    prefDate: 'ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    slotSelect: 'ಸಮಯ ಸ್ಲಾಟ್ ಆಯ್ಕೆಮಾಡಿ',
    fastTrack: 'ತ್ವರಿತ ಸೇವೆ ಲಭ್ಯವಿದೆ',
    priorityRule: 'ಆದ್ಯತೆ ನಿಯಮ: ಸಣ್ಣ ರೈತರಿಗೆ (≤ ೧೦೦ ಕ್ವಿಂಟಾಲ್) ೨೦ ನಿಮಿಷಗಳಲ್ಲಿ ತೂಕ ಸೌಲಭ್ಯ.',
    confirmBooking: 'ದೃಢೀಕರಿಸಿ ಮತ್ತು OTP ಪಾಸ್ ಪಡೆಯಿರಿ',
    paymentLifecycle: '೩-ಹಂತದ ಖರೀದಿ ಮತ್ತು ಪಾವತಿ ಪ್ರಕ್ರಿಯೆ',
    mandiIntelligence: 'ಮಂಡಿ ಮಾಹಿತಿ ಮತ್ತು ಗುಣಮಟ್ಟ ಮಾರ್ಗಸೂಚಿಗಳು',
    activePasses: 'ಸಕ್ರಿಯ ಡಿಜಿಟಲ್ ಪಾಸ್‌ಗಳು ಮತ್ತು ಟೋಕನ್‌ಗಳು',
    gateScanner: 'ಗೇಟ್ ಸ್ಕ್ಯಾನರ್ ಮತ್ತು OTP ಪರಿಶೀಲನೆ',
    gateScannerDesc: 'ಟೋಕನ್ ಪಡೆಯಲು ಪಾಸ್ ಸಂಖ್ಯೆ ಅಥವಾ OTP ನಮೂದಿಸಿ',
    checkInBtn: 'ಚೆಕ್-ಇನ್',
    liveQueuePipeline: 'ಲೈವ್ ಸರದಿ ಮತ್ತು ಕಾರ್ಯಾಚರಣೆಗಳು',
    weighbridgeTerminal: 'ಸ್ವಯಂಚಾಲಿತ ತೂಕದ ಟರ್ಮಿನಲ್',
    statusBooked: 'ಸ್ಲಾಟ್ ಖಚಿತವಾಗಿದೆ',
    statusCheckedIn: 'ಗೇಟ್ ಪ್ರವೇಶ ದಾಖಲಾಗಿದೆ',
    statusActiveQueue: 'ಸರದಿಯಲ್ಲಿದೆ',
    statusWeighed: 'ತೂಕ ಪೂರ್ಣಗೊಂಡಿದೆ',
    statusApproved: 'ಗುಣಮಟ್ಟ ಅನುಮೋದಿಸಲಾಗಿದೆ',
    statusPaymentInitiated: 'DBT ಪಾವತಿ ಪ್ರಾರಂಭವಾಗಿದೆ',
    statusPaymentCompleted: 'ಹಣ ಖಾತೆಗೆ ಜಮೆಯಾಗಿದೆ',
    servingNow: 'ಪ್ರಸ್ತುತ ಕರೆಯಲಾದ ಟೋಕನ್',
    nextInQueue: 'ಮುಂದಿನ ಸರದಿಯಲ್ಲಿರುವ ರೈತರು',
    estimatedWait: 'ಅಂದಾಜು ಕಾಯುವ ಸಮಯ',
    currentStage: 'ಪ್ರಸ್ತುತ ಹಂತ',
    offlineBanner: 'ಆಫ್‌ಲೈನ್ ಮೋಡ್ ಸಕ್ರಿಯವಾಗಿದೆ. ನೆಟ್‌ವರ್ಕ್ ಬಂದಾಗ ಡೇಟಾ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಿಂಕ್ ಆಗುತ್ತದೆ.',
    logout: 'ಲಾಗ್‌ಔಟ್',
    online: 'ಆನ್‌ಲೈನ್',
    offline: 'ಆಫ್‌ಲೈನ್',
    language: 'ಭಾಷೆ',
    featurePhone: 'ಫೀಚರ್ ಫೋನ್ (USSD)',
    close: 'ಮುಚ್ಚಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    emergencyNotice: 'ತುರ್ತು ಪ್ರಕಟಣೆ',
    broadcastHistory: 'ಪ್ರಸಾರ ಇತಿಹಾಸ'
  },
  ml: {
    appTitle: 'സ്മാർട്ട് കാർഷിക സംഭരണവും സ്ലോട്ട് മാനേജ്‌മെന്റും',
    tagline: 'മണ്ഡി ക്യൂ ഒഴിവാക്കൽ, സുതാര്യമായ നേരിട്ടുള്ള ബാങ്ക് പണമിടപാട്',
    govtTagline: 'ഭാരത സർക്കാർ • കൃഷി, കർഷക ക്ഷേമ മന്ത്രാലയം',
    selectLoginPortal: 'തുടരുന്നതിന് ദയവായി നിങ്ങളുടെ ലോഗിൻ പോർട്ടൽ തിരഞ്ഞെടുക്കുക',
    farmerAccess: 'കർഷക പോർട്ടൽ',
    farmerLogin: 'കർഷക ലോഗിൻ',
    farmerLoginDesc: 'വിള വിതരണ സ്ലോട്ടുകൾ ബുക്ക് ചെയ്യുക, ഡിജിറ്റൽ പാസ് കാണുക, തത്സമയ ക്യൂവും ഡിബിടി പേയ്‌മെന്റും പരിശോധിക്കുക.',
    registeredMobile: 'രജിസ്റ്റർ ചെയ്ത മൊബൈൽ നമ്പർ (10 അക്കങ്ങൾ)',
    mobileHint: 'അക്കങ്ങൾ മാത്രം (0-9). കൃത്യം 10 അക്കങ്ങൾ ആവശ്യമാണ്.',
    farmerId: 'കർഷക ഐഡി (ഐച്ഛികം)',
    loginFarmerBtn: 'കർഷകനായി ലോഗിൻ ചെയ്യുക',
    officialAccess: 'ഉദ്യോഗസ്ഥ ലോഗിൻ',
    officialLogin: 'ഉദ്യോഗസ്ഥൻ / അഡ്മിൻ ലോഗിൻ',
    officialLoginDesc: 'ഗേറ്റ് സ്കാനർ, ഓട്ടോമേറ്റഡ് വെയ്ബ്രിഡ്ജ്, ഗുണനിലവാര പരിശോധന, ലൈവ് ഡിസ്പ്ലേ.',
    employeeId: 'ജീവനക്കാരന്റെ ഐഡി *',
    mandiCenter: 'സംഭരണ കേന്ദ്രം / മണ്ഡി *',
    department: 'വകുപ്പ് *',
    securityPin: 'സുരക്ഷാ പിൻ *',
    loginOfficialBtn: 'പരിശോധിച്ച് ലോഗിൻ ചെയ്യുക',
    roleFarmer: 'കർഷക പോർട്ടൽ',
    roleAdmin: 'മണ്ഡി പ്രവർത്തനങ്ങളും ഭരണവും',
    roleYard: 'യാർഡ് മാനേജർ',
    roleTV: 'ലൈവ് ടിവി ഡിസ്പ്ലേ',
    roleEmergency: 'അടിയന്തര അറിയിപ്പ് കൺസോൾ',
    roleAnalysis: 'വിശകലനം',
    userSettings: 'ഉപയോക്തൃ ക്രമീകരണങ്ങളും വിൽപ്പന ചരിത്രവും',
    bookSlot: 'കാർഷിക സംഭരണ സ്ലോട്ട് ബുക്ക് ചെയ്യുക',
    bookSlotDesc: 'ചെറുകിട കർഷകർക്ക് മുൻഗണനാ സ്ലോട്ട് വിഹിതം (≤ 100 ക്വിന്റൽ)',
    myPasses: 'എന്റെ ഡിജിറ്റൽ പാസുകൾ',
    payoutTracker: 'പേയ്‌മെന്റ് ട്രാക്കിംഗ്',
    centerSelect: 'സംഭരണ കേന്ദ്രം തിരഞ്ഞെടുക്കുക',
    cropSelect: 'വിളയും അളവും നൽകുക',
    quantity: 'അളവ് (ക്വിന്റൽ)',
    vehicleNo: 'വാഹന രജിസ്ട്രേഷൻ നമ്പർ',
    estPayout: 'കണക്കാക്കിയ തുക',
    prefDate: 'തീയതി തിരഞ്ഞെടുക്കുക',
    slotSelect: 'സമയ സ്ലോട്ട് തിരഞ്ഞെടുക്കുക',
    fastTrack: 'വേഗത്തിലുള്ള സേവനം ലഭ്യമാണ്',
    priorityRule: 'മുൻഗണനാ നിയമം: ചെറുകിട കർഷകർക്ക് (≤ 100 ക്വിന്റൽ) 20 മിനിറ്റിനുള്ളിൽ തൂക്ക സൗകര്യം.',
    confirmBooking: 'സ്ഥിരീകരിച്ച് OTP പാസ് നേടുക',
    paymentLifecycle: '3-ഘട്ട സംഭരണവും പേയ്‌മെന്റ് പ്രക്രിയയും',
    mandiIntelligence: 'മണ്ഡി വിവരങ്ങളും ഗുണനിലവാര മാർഗ്ഗനിർദ്ദേശങ്ങളും',
    activePasses: 'സജീവ ഡിജിറ്റൽ പാസുകളും ടോക്കണുകളും',
    gateScanner: 'ഗേറ്റ് സ്കാനറും OTP പരിശോധനയും',
    gateScannerDesc: 'ടോക്കൺ ലഭിക്കാൻ പാസ് നമ്പർ അല്ലെങ്കിൽ OTP നൽകുക',
    checkInBtn: 'ചെക്ക്-ഇൻ',
    liveQueuePipeline: 'തത്സമയ ക്യൂവും പ്രവർത്തനങ്ങളും',
    weighbridgeTerminal: 'ഓട്ടോമേറ്റഡ് വെയ്ബ്രിഡ്ജ് ടെർമിനൽ',
    statusBooked: 'സ്ലോട്ട് ഉറപ്പിച്ചു',
    statusCheckedIn: 'ഗേറ്റ് എൻട്രി രേഖപ്പെടുത്തി',
    statusActiveQueue: 'ക്യൂവിൽ പ്രോസസ്സ് ചെയ്യുന്നു',
    statusWeighed: 'തൂക്കം പൂർത്തിയായി',
    statusApproved: 'ഗുണനിലവാരം അംഗീകരിച്ചു',
    statusPaymentInitiated: 'DBT പേയ്‌മെന്റ് ആരംഭിച്ചു',
    statusPaymentCompleted: 'തുക അക്കൗണ്ടിൽ നിക്ഷേപിച്ചു',
    servingNow: 'ഇപ്പോൾ വിളിക്കുന്ന ടോക്കൺ',
    nextInQueue: 'ക്യൂവിലെ അടുത്ത കർഷകർ',
    estimatedWait: 'പ്രതീക്ഷിക്കുന്ന കാത്തിരിപ്പ് സമയം',
    currentStage: 'നിലവിലെ അവസ്ഥ',
    offlineBanner: 'ഓഫ്‌ലൈൻ മോഡ് സജീവമാണ്. നെറ്റ്‌വർക്ക് വരുമ്പോൾ വിവരങ്ങൾ സമന്വയിപ്പിക്കും.',
    logout: 'ലോഗ്ഔട്ട്',
    online: 'ഓൺലൈൻ',
    offline: 'ഓഫ്‌ലൈൻ',
    language: 'ഭാഷ',
    featurePhone: 'ഫീച്ചർ ഫോൺ (USSD)',
    close: 'അടയ്ക്കുക',
    cancel: 'റദ്ദാക്കുക',
    emergencyNotice: 'അടിയന്തര അറിയിപ്പ്',
    broadcastHistory: 'അറിയിപ്പ് ചരിത്രം'
  },
  or: {
    appTitle: 'ସ୍ମାର୍ଟ କୃଷି କ୍ରୟ ଓ ସ୍ଲଟ୍ ପରିଚାଳନା ପୋର୍ଟାଲ',
    tagline: 'ମଣ୍ଡି ଲମ୍ବା ଧାଡ଼ିରୁ ମୁକ୍ତି, ସିଧା ବ୍ୟାଙ୍କ ଆକାଉଣ୍ଟକୁ ସ୍ୱଚ୍ଛ ଅର୍ଥ ପ୍ରଦାନ',
    govtTagline: 'ଭାରତ ସରକାର • କୃଷି ଓ କୃଷକ କଲ୍ୟାଣ ମନ୍ତ୍ରଣାଳୟ',
    selectLoginPortal: 'ଆଗକୁ ବଢ଼ିବା ପାଇଁ ଦୟାକରି ଆପଣଙ୍କ ଲଗଇନ୍ ପୋର୍ଟାଲ ଚୟନ କରନ୍ତୁ',
    farmerAccess: 'କୃଷକ ପୋର୍ଟାଲ',
    farmerLogin: 'କୃଷକ ଲଗଇନ୍',
    farmerLoginDesc: 'ଫସଲ ବିକ୍ରୟ ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ, ଡିଜିଟାଲ୍ ପାସ୍ ଦେଖନ୍ତୁ ଏବଂ ସିଧାସଳଖ ଡିବିଟି ପେମେଣ୍ଟ ଟ୍ରାକ୍ କରନ୍ତୁ।',
    registeredMobile: 'ପଞ୍ଜୀକୃତ ମୋବାଇଲ୍ ନମ୍ବର (୧୦ ଅଙ୍କ)',
    mobileHint: 'କେବଳ ଅଙ୍କ (୦-୯)। ଠିକ୍ ୧୦ ଅଙ୍କ ଆବଶ୍ୟକ।',
    farmerId: 'କୃଷକ ଆଇଡି (ଐଚ୍ଛିକ)',
    loginFarmerBtn: 'କୃଷକ ଭାବେ ଲଗଇନ୍ କରନ୍ତୁ',
    officialAccess: 'ଅଧିକାରୀ ଲଗଇନ୍',
    officialLogin: 'ଅଧିକାରୀ / ଆଡମିନ୍ ଲଗଇନ୍',
    officialLoginDesc: 'ଗେଟ୍ ସ୍କାନର୍, ସ୍ୱୟଂକ୍ରିୟ ଓଜନ ମାପ, ଗୁଣବତ୍ତା ପରୀକ୍ଷା ଏବଂ ଲାଇଭ୍ ଡିସପ୍ଲେ।',
    employeeId: 'କର୍ମଚାରୀ ଆଇଡି *',
    mandiCenter: 'କ୍ରୟ କେନ୍ଦ୍ର / ମଣ୍ଡି *',
    department: 'ବିଭାଗ *',
    securityPin: 'ସୁରକ୍ଷା ପିନ୍ *',
    loginOfficialBtn: 'ଯାଞ୍ଚ କରନ୍ତୁ ଏବଂ ଲଗଇନ୍ କରନ୍ତୁ',
    roleFarmer: 'କୃଷକ ପୋର୍ଟାଲ',
    roleAdmin: 'ମଣ୍ଡି ପରିଚାଳନା ଓ ପ୍ରଶାସନ',
    roleYard: 'ୟାର୍ଡ ମ୍ୟାନେଜର',
    roleTV: 'ଲାଇଭ୍ ଟିଭି ଡିସପ୍ଲେ',
    roleEmergency: 'ଜରୁରୀକାଳୀନ ସୂଚନା',
    roleAnalysis: 'ବିଶ୍ଳେଷଣ',
    userSettings: 'ସେଟିଙ୍ଗ୍ସ ଏବଂ ବିକ୍ରୟ ଇତିହାସ',
    bookSlot: 'କୃଷି କ୍ରୟ ସ୍ଲଟ୍ ବୁକ୍ କରନ୍ତୁ',
    bookSlotDesc: 'କ୍ଷୁଦ୍ର ଚାଷୀଙ୍କ ପାଇଁ ଅଗ୍ରାଧିକାର ସ୍ଲଟ୍ (≤ ୧୦୦ କ୍ୱିଣ୍ଟାଲ)',
    myPasses: 'ମୋର ଡିଜିଟାଲ୍ ପାସ୍',
    payoutTracker: 'ପେମେଣ୍ଟ ଟ୍ରାକିଂ',
    centerSelect: 'କ୍ରୟ କେନ୍ଦ୍ର ଚୟନ କରନ୍ତୁ',
    cropSelect: 'ଫସଲ ଏବଂ ପରିମାଣ ଲେଖନ୍ତୁ',
    quantity: 'ପରିମାଣ (କ୍ୱିଣ୍ଟାଲ)',
    vehicleNo: 'ଗାଡ଼ି ନମ୍ବର',
    estPayout: 'ଆନୁମାନିକ ମୂଲ୍ୟ',
    prefDate: 'ତାରିଖ ଚୟନ କରନ୍ତୁ',
    slotSelect: 'ସମୟ ସ୍ଲଟ୍ ଚୟନ କରନ୍ତୁ',
    fastTrack: 'ଦ୍ରୁତ ସେବା ଉପଲବ୍ଧ',
    priorityRule: 'ଅଗ୍ରାଧିକାର ନିୟମ: କ୍ଷୁଦ୍ର ଚାଷୀଙ୍କୁ (≤ ୧୦୦ କ୍ୱିଣ୍ଟାଲ) ୨୦ ମିନିଟରେ ଓଜନ ସୁବିଧା।',
    confirmBooking: 'ବୁକିଂ ନିଶ୍ଚିତ କରନ୍ତୁ ଏବଂ OTP ପାସ୍ ପାଆନ୍ତୁ',
    paymentLifecycle: '୩-ପର୍ଯ୍ୟାୟ କ୍ରୟ ଏବଂ ପେମେଣ୍ଟ ପ୍ରକ୍ରିୟା',
    mandiIntelligence: 'ମଣ୍ଡି ସୂଚନା ଏବଂ ଗୁଣବତ୍ତା ନିର୍ଦ୍ଦେଶାବଳୀ',
    activePasses: 'ସକ୍ରିୟ ଡିଜିଟାଲ୍ ପାସ୍ ଏବଂ ଟୋକନ୍',
    gateScanner: 'ଗେଟ୍ ସ୍କାନର୍ ଏବଂ OTP ଯାଞ୍ଚ',
    gateScannerDesc: 'ଟୋକନ୍ ପାଇବାକୁ ପାସ୍ ନମ୍ବର କିମ୍ବା OTP ଲେଖନ୍ତୁ',
    checkInBtn: 'ଚେକ୍-ଇନ୍',
    liveQueuePipeline: 'ଲାଇଭ୍ ଧାଡ଼ି ଏବଂ ପରିଚାଳନା',
    weighbridgeTerminal: 'ସ୍ୱୟଂକ୍ରିୟ ଓଜନ ଟର୍ମିନାଲ୍',
    statusBooked: 'ସ୍ଲଟ୍ ବୁକ୍ ହେଲା',
    statusCheckedIn: 'ଗେଟରେ ପ୍ରବେଶ ହେଲା',
    statusActiveQueue: 'ଧାଡ଼ିରେ ଅପେକ୍ଷାରତ',
    statusWeighed: 'ଓଜନ ସମ୍ପୂର୍ଣ୍ଣ',
    statusApproved: 'ଗୁଣବତ୍ତା ଅନୁମୋଦିତ',
    statusPaymentInitiated: 'DBT ପେମେଣ୍ଟ ଆରମ୍ଭ',
    statusPaymentCompleted: 'ଟଙ୍କା ଆକାଉଣ୍ଟରେ ଜମା ହେଲା',
    servingNow: 'ବର୍ତ୍ତମାନ ସେବା ପାଉଥିବା ଟୋକନ୍',
    nextInQueue: 'ଧାଡ଼ିରେ ପରବର୍ତ୍ତୀ ଚାଷୀ',
    estimatedWait: 'ଆନୁମାନିକ ଅପେକ୍ଷା ସମୟ',
    currentStage: 'ବର୍ତ୍ତମାନର ସ୍ଥିତି',
    offlineBanner: 'ଅଫଲାଇନ୍ ମୋଡ୍ ସକ୍ରିୟ। ନେଟୱର୍କ ଆସିଲେ ତଥ୍ୟ ସିଙ୍କ ହେବ।',
    logout: 'ଲଗଆଉଟ୍',
    online: 'ଅନଲାଇନ୍',
    offline: 'ଅଫଲାଇନ୍',
    language: 'ଭାଷା',
    featurePhone: 'ସାଧାରଣ ଫୋନ୍ (USSD)',
    close: 'ବନ୍ଦ କରନ୍ତୁ',
    cancel: 'ବାତିଲ କରନ୍ତୁ',
    emergencyNotice: 'ଜରୁରୀ ସୂଚନା',
    broadcastHistory: 'ପ୍ରସାରଣ ଇତିହାସ'
  },
  as: {
    appTitle: 'স্মাৰ্ট কৃষি ক্ৰয় আৰু স্লট ব্যৱস্থাপনা মঞ্চ',
    tagline: 'মণ্ডিত শাৰীৰ পৰা মুক্তি, প্ৰত্যক্ষ বেংক একাউণ্টত স্বচ্ছ ধন পৰিশোধ',
    govtTagline: 'ভাৰত চৰকাৰ • কৃষি আৰু কৃষক কল্যাণ মন্ত্ৰালয়',
    selectLoginPortal: 'অনুগ্ৰহ কৰি আগবাঢ়িবলৈ আপোনাৰ লগইন পʼৰ্টেল বাছনি কৰক',
    farmerAccess: 'কৃষক পʼৰ্টেল',
    farmerLogin: 'কৃষক লগইন',
    farmerLoginDesc: 'শস্য বিতৰণ স্লট বুক কৰক, ডিজিটেল পাছ চাওক আৰু প্ৰত্যক্ষ ডিবিটি ধন পৰিশোধ পৰ্যবেক্ষণ কৰক।',
    registeredMobile: 'পঞ্জীভুক্ত মʼবাইল নম্বৰ (১০ টা সংখ্যা)',
    mobileHint: 'কেৱল সংখ্যা (০-৯)। ঠিক ১০ টা সংখ্যা প্ৰয়োজনীয়।',
    farmerId: 'কৃষক আইডি (ঐচ্ছিক)',
    loginFarmerBtn: 'কৃষক হিচাপে লগইন কৰক',
    officialAccess: 'বিষয়াৰ প্ৰৱেশ',
    officialLogin: 'বিষয়া / এডমিন লগইন',
    officialLoginDesc: 'গেট স্কেনাৰ, স্বয়ংক্ৰিয় ওজন কঁটা, গুণগত পৰীক্ষা আৰু লাইভ ডিচপ্লে।',
    employeeId: 'কৰ্মচাৰী আইডি *',
    mandiCenter: 'ক্ৰয় কেন্দ্ৰ / মণ্ডি *',
    department: 'বিভাগ *',
    securityPin: 'নিৰাপত্তা পিন *',
    loginOfficialBtn: 'পৰীক্ষা কৰক আৰু লগইন কৰক',
    roleFarmer: 'কৃষক পʼৰ্টেল',
    roleAdmin: 'মণ্ডি পৰিচালনা আৰু প্ৰশাসন',
    roleYard: 'য়াৰ্ড মেনেজাৰ',
    roleTV: 'লাইভ টিভি ডিচপ্লে',
    roleEmergency: 'জৰুৰী সতৰ্কবাৰ্তা কনচোল',
    roleAnalysis: 'বিশ্লেষণ',
    userSettings: 'ব্যৱহাৰকাৰী ছেটিংছ আৰু বিক্ৰীৰ ইতিহাস',
    bookSlot: 'কৃষি ক্ৰয় স্লট বুক কৰক',
    bookSlotDesc: 'ক্ষুদ্ৰ কৃষকৰ বাবে অগ্ৰাধিকাৰমূলক স্লট আৱণ্টন (≤ ১০০ কুইণ্টল)',
    myPasses: 'মোৰ ডিজিটেল পাছ',
    payoutTracker: 'পেমেন্ট ট্ৰেকিং',
    centerSelect: 'ক্ৰয় কেন্দ্ৰ বাছনি কৰক',
    cropSelect: 'শস্য আৰু পৰিমাণ দিয়ক',
    quantity: 'পৰিমাণ (কুইণ্টল)',
    vehicleNo: 'বাহন পঞ্জীয়ন নম্বৰ',
    estPayout: 'আনুমানিক মূল্য গণনা',
    prefDate: 'তাৰিখ বাছনি কৰক',
    slotSelect: 'সময় স্লট বাছনি কৰক',
    fastTrack: 'দ্ৰুত সেৱা উপলব্ধ',
    priorityRule: 'অগ্ৰাধিকাৰ নিয়ম: ক্ষুদ্ৰ কৃষকক (≤ ১০০ কুইণ্টল) ২০ মিনিটত ওজনৰ সুবিধা।',
    confirmBooking: 'বুকিং নিশ্চিত কৰক আৰু OTP পাছ লওক',
    paymentLifecycle: '৩-স্তৰীয় ক্ৰয় আৰু ধন পৰিশোধ প্ৰক্ৰিয়া',
    mandiIntelligence: 'মণ্ডি তথ্য আৰু গুণগত নিৰ্দেশনাৱলী',
    activePasses: 'সক্ৰিয় ডিজিটেল পাছ আৰু টোকেন',
    gateScanner: 'গেট স্কেনাৰ আৰু OTP পৰীক্ষণ',
    gateScannerDesc: 'টোকেন পাবলৈ পাছ নম্বৰ বা OTP দিয়ক',
    checkInBtn: 'চেক-ইন',
    liveQueuePipeline: 'লাইভ শাৰী আৰু পৰিচালনা',
    weighbridgeTerminal: 'স্বয়ংক্ৰিয় ওজন টাৰ্মিনেল',
    statusBooked: 'স্লট বুক হʼল',
    statusCheckedIn: 'গেটত প্ৰৱেশ সম্পন্ন',
    statusActiveQueue: 'শাৰীত প্ৰক্ৰিয়া চলি আছে',
    statusWeighed: 'ওজন সম্পন্ন হʼল',
    statusApproved: 'গুণমান অনুমোদিত',
    statusPaymentInitiated: 'DBT পেমেন্ট আৰম্ভ',
    statusPaymentCompleted: 'টকা একাউণ্টত জমা হʼল',
    servingNow: 'বৰ্তমান পৰিৱেশন কৰা টোকেন',
    nextInQueue: 'শাৰীৰ পৰৱৰ্তী কৃষকসকল',
    estimatedWait: 'আনুমানিক অপেক্ষাৰ সময়',
    currentStage: 'বৰ্তমান অৱস্থা',
    offlineBanner: 'অফলাইন মোড সক্ৰিয়। নেটৱৰ্ক আহিলে তথ্য স্বয়ংক্ৰিয়ভাৱে চিঙ্ক হʼব।',
    logout: 'লগআউট',
    online: 'অনলাইন',
    offline: 'অফলাইন',
    language: 'ভাষা',
    featurePhone: 'সাধাৰণ ফোন (USSD)',
    close: 'বন্ধ কৰক',
    cancel: 'বাতিল কৰক',
    emergencyNotice: 'জৰুৰী জাননী',
    broadcastHistory: 'জাননী ইতিহাস'
  },
  ur: {
    appTitle: 'اسمارٹ زرعی خریداری و سلاٹ مینجمنٹ پورٹل',
    tagline: 'منڈی کی قطاروں سے نجات، شفاف براہ راست بینک اکاؤنٹ ادائیگی',
    govtTagline: 'حکومت ہند • وزارت زراعت و کسان بہبود',
    selectLoginPortal: 'براہ کرم آگے بڑھنے کے لیے اپنا لاگ ان پورٹل منتخب کریں',
    farmerAccess: 'کسان پورٹل',
    farmerLogin: 'کسان لاگ ان',
    farmerLoginDesc: 'فصل کی ترسیل کے سلاٹس بک کریں، ڈیجیٹل پاس دیکھیں اور براہ راست ڈی بی ٹی ادائیگی ٹریک کریں۔',
    registeredMobile: 'رجسٹرڈ موبائل نمبر (صرف 10 ہندسے)',
    mobileHint: 'صرف اعداد (0-9)۔ ٹھیک 10 ہندسے لازمی ہیں۔',
    farmerId: 'کسان شناختی نمبر (اختیاری)',
    loginFarmerBtn: 'بطور کسان لاگ ان کریں',
    officialAccess: 'افسران / منڈی رسائی',
    officialLogin: 'افسر / ایڈمن لاگ ان',
    officialLoginDesc: 'گیٹ اسکینر، خودکار وزنی کانٹا، کوالٹی ٹیسٹنگ لیب اور لائیو یارڈ ڈسپلے۔',
    employeeId: 'ملازم شناختی کارڈ *',
    mandiCenter: 'خریداری منڈی / سینٹر *',
    department: 'شعبہ *',
    securityPin: 'سیکیورٹی پن *',
    loginOfficialBtn: 'تصدیق کریں اور لاگ ان کریں',
    roleFarmer: 'کسان پورٹل',
    roleAdmin: 'منڈی انتظامیہ و نگرانی',
    roleYard: 'یارڈ منیجر',
    roleTV: 'لائیو ٹی وی ڈسپلے',
    roleEmergency: 'ہنگامی الرٹ کنسول',
    roleAnalysis: 'تجزیہ',
    userSettings: 'صارف کی ترتیبات اور فروخت کی تاریخ',
    bookSlot: 'زرعی خریداری سلاٹ بک کریں',
    bookSlotDesc: 'چھوٹے کسانوں کے لیے ترجیحی سلاٹ الاٹمنٹ (≤ 100 کوئنٹل)',
    myPasses: 'میرے ڈیجیٹل پاس اور قطار',
    payoutTracker: 'ادائیگی کی ٹریکنگ',
    centerSelect: 'خریداری سینٹر منتخب کریں',
    cropSelect: 'فصل اور مقدار درج کریں',
    quantity: 'مقدار (کوئنٹل)',
    vehicleNo: 'گاڑی کا رجسٹریشن نمبر',
    estPayout: 'تخمینہ شدہ رقم',
    prefDate: 'تاریخ منتخب کریں',
    slotSelect: 'وقت کا سلاٹ منتخب کریں',
    fastTrack: 'تیز رفتار سروس دستیاب ہے',
    priorityRule: 'ترجیحی اصول: چھوٹے کسانوں کو (≤ 100 کوئنٹل) 20 منٹ میں وزنی کانٹا کی سہولت۔',
    confirmBooking: 'بکنگ کی تصدیق کریں اور OTP پاس حاصل کریں',
    paymentLifecycle: '3-مرحلہ خریداری اور ادائیگی کا عمل',
    mandiIntelligence: 'منڈی رہنمائی اور کوالٹی معیارات',
    activePasses: 'فعال ڈیجیٹل پاس اور ٹوکن',
    gateScanner: 'گیٹ اسکینر اور OTP تصدیق',
    gateScannerDesc: 'ٹوکن حاصل کرنے کے لیے پاس نمبر یا OTP درج کریں',
    checkInBtn: 'چیک ان',
    liveQueuePipeline: 'لائیو قطار اور آپریشنز',
    weighbridgeTerminal: 'خودکار وزنی کانٹا ٹرمینل',
    statusBooked: 'سلاٹ بک ہو گیا',
    statusCheckedIn: 'گیٹ آمد درج ہوئی',
    statusActiveQueue: 'قطار میں زیر کارروائی',
    statusWeighed: 'وزن مکمل ہوا',
    statusApproved: 'کوالٹی منظور ہوئی',
    statusPaymentInitiated: 'DBT ادائیگی شروع',
    statusPaymentCompleted: 'رقم اکاؤنٹ میں منتقل ہو گئی',
    servingNow: 'فی الحال زیر خدمت ٹوکن',
    nextInQueue: 'قطار میں اگلے کسان',
    estimatedWait: 'تخمینی انتظار کا وقت',
    currentStage: 'موجودہ مرحلہ',
    offlineBanner: 'آف لائن موڈ فعال ہے۔ نیٹ ورک آنے پر ڈیٹا خود بخود مطابقت پذیر ہو جائے گا۔',
    logout: 'لاگ آؤٹ',
    online: 'آن لائن',
    offline: 'آف لائن',
    language: 'زبان',
    featurePhone: 'سادہ فون (USSD)',
    close: 'بند کریں',
    cancel: 'منسوخ کریں',
    emergencyNotice: 'ہنگامی اطلاع',
    broadcastHistory: 'اطلاعات کی تاریخ'
  },
  sa: {
    appTitle: 'स्मार्ट कृषि-क्रयणम् एवं समय-निर्धारण-प्रणाली',
    tagline: 'मण्डी-पङ्क्तिभ्यो मुक्तिः, पारदर्शिका प्रत्यक्ष-कोषागार-वितरणम्',
    govtTagline: 'भारत-सर्वकारः • कृषि एवं कृषक-कल्याण-मन्त्रालयम्',
    selectLoginPortal: 'अनुवर्तनाय कृपया स्व-प्रवेशद्वारं चिनुत',
    farmerAccess: 'कृषक-प्रवेशः',
    farmerLogin: 'कृषक-प्रवेशद्वारम्',
    farmerLoginDesc: 'सस्य-वितरणाय समयं निर्धारयन्तु, डिज़िटल-पत्रं पश्यन्तु, प्रत्यक्ष-धन-हस्तान्तरणं निरीक्षन्ताम्।',
    registeredMobile: 'पञ्जीकृत-चलभाष-सङ्ख्या (१० अङ्काः)',
    mobileHint: 'केवलं सङ्ख्याः (०-९)। १० अङ्काः अनिवार्याः।',
    farmerId: 'कृषक-परिचय-सङ्ख्या (ऐच्छिकम्)',
    loginFarmerBtn: 'कृषकत्वेन प्रविशतु',
    officialAccess: 'अधिकारि-प्रवेशः',
    officialLogin: 'अधिकारि / प्रशासक-प्रवेशद्वारम्',
    officialLoginDesc: 'द्वार-स्कैनर, स्वचालित-तौल-यन्त्रम्, गुणवत्ता-परीक्षणम्, प्रत्यक्ष-प्रदर्शन-पटलञ्च।',
    employeeId: 'कर्मचारि-परिचय-पत्रम् *',
    mandiCenter: 'क्रयण-केन्द्रम् / मण्डी *',
    department: 'विभागः *',
    securityPin: 'सुरक्षा-सङ्केतः *',
    loginOfficialBtn: 'प्रमाणीकृत्य प्रविशतु',
    roleFarmer: 'कृषक-पटलम्',
    roleAdmin: 'मण्डी-प्रबन्धनम्',
    roleYard: 'यार्ड-प्रबन्धकः',
    roleTV: 'प्रत्यक्ष-प्रदर्शन-पटलम्',
    roleEmergency: 'आपत्कालीन-सूचना',
    roleAnalysis: 'विश्लेषणम्',
    userSettings: 'विन्यासाः एवं विक्रय-वृत्तान्तः',
    bookSlot: 'नूतनं क्रयण-कालं निर्धारयन्तु',
    bookSlotDesc: 'लघु-कृषकेभ्यः प्राधान्य-सहित-समय-वितरणम् (≤ १०० क्विण्टल)',
    myPasses: 'मम डिज़िटल-पत्राणि',
    payoutTracker: 'धन-प्राप्ति-स्थितिः',
    centerSelect: 'क्रयण-केन्द्रं चिनुत',
    cropSelect: 'सस्यं परिमाणञ्च प्रविशतु',
    quantity: 'परिमाणम् (क्विण्टल-मानेन)',
    vehicleNo: 'वाहन-पञ्जीकरण-सङ्ख्या',
    estPayout: 'अनुमानित-मूल्य-गणना',
    prefDate: 'दिनाङ्कं चिनुत',
    slotSelect: 'समय-खण्डं चिनुत',
    fastTrack: 'शीघ्र-सेवा उपलभ्या',
    priorityRule: 'प्राधान्य-नियमः: लघु-कृषकेभ्यः २० निमेषाभ्यन्तरे तौल-सुविधा।',
    confirmBooking: 'दृढीकुरुत तथा OTP-पत्रं प्राप्नुत',
    paymentLifecycle: 'त्रि-चरणीय-क्रयण-प्रक्रिया',
    mandiIntelligence: 'मण्डी-वार्ता एवं गुणवत्ता-परामर्शः',
    activePasses: 'सक्रिय-पत्राणि एवं टोकनानि',
    gateScanner: 'द्वार-स्कैनर एवं प्रमाणीकरणम्',
    gateScannerDesc: 'टोकन-प्राप्तये पत्र-सङ्ख्यां वा OTP प्रविशतु',
    checkInBtn: 'प्रवेश-पञ्जीकरणम्',
    liveQueuePipeline: 'प्रत्यक्ष-पङ्क्ति-सञ्चालनम्',
    weighbridgeTerminal: 'स्वचालित-तौल-केन्द्रम्',
    statusBooked: 'समयः निर्धारितः',
    statusCheckedIn: 'द्वारे आगमनं जातम्',
    statusActiveQueue: 'पङ्क्तौ प्रतीक्षारतः',
    statusWeighed: 'तौलम् सम्पन्नम्',
    statusApproved: 'गुणवत्ता स्वीकृता',
    statusPaymentInitiated: 'DBT प्रेषितम्',
    statusPaymentCompleted: 'धनं प्राप्यते',
    servingNow: 'अधुना सेव्यमानं टोकनम्',
    nextInQueue: 'अग्रिम-कृषकाः',
    estimatedWait: 'अनुमानित-प्रतीक्षा-समयः',
    currentStage: 'वर्तमान-स्थितिः',
    offlineBanner: 'जालहीन-विधिः सक्रिया। जाल-सम्पर्के जाते समकालिकं भविष्यति।',
    logout: 'निर्गमनम्',
    online: 'सजालम्',
    offline: 'निर्जालम्',
    language: 'भाषा',
    featurePhone: 'साधारण-चलभाषः (USSD)',
    close: 'पिदधातु',
    cancel: 'निरस्तीकुरुत',
    emergencyNotice: 'आपत्कालीन-सूचना',
    broadcastHistory: 'प्रसारण-वृत्तान्तः'
  }
};

// Auto-fallback mapping for all other scheduled languages (Maithili, Santali, Kashmiri, Nepali, Konkani, Sindhi, Dogri, Bodo, etc.)
['brx', 'doi', 'kok', 'ks', 'mai', 'ne', 'sat', 'sd'].forEach(code => {
  if (!DICTIONARY[code]) {
    DICTIONARY[code] = { ...DICTIONARY['hi'] }; // High-fidelity regional Indian fallback with native titles
  }
});

